import { createContext, useContext, useEffect, useState } from "react";
const Context = createContext(null);
const key = "smart-building-language";
const staffDashboardWords = {
  en: {
    "staffDashboard.eyebrow": "CAMPUS FACILITIES",
    "staffDashboard.loading": "Loading…",
    "staffDashboard.retry": "Try again",
    "staffDashboard.welcome": "Welcome back,",
    "staffDashboard.description": "Here is an overview of your maintenance requests and campus buildings.",
    "staffDashboard.total": "TOTAL REQUESTS",
    "staffDashboard.pending": "PENDING",
    "staffDashboard.inProgress": "IN PROGRESS",
    "staffDashboard.resolved": "RESOLVED",
    "staffDashboard.allSubmissions": "All your submissions",
    "staffDashboard.awaiting": "Awaiting attention",
    "staffDashboard.inCare": "Being looked after",
    "staffDashboard.completed": "Requests completed",
    "staffDashboard.prompt": "Something needs attention?",
    "staffDashboard.promptHelp": "Report a facilities issue and follow its progress.",
    "staffDashboard.newMaintenance": "New Maintenance Request",
    "staffDashboard.recent": "Recent requests",
    "staffDashboard.viewAll": "View all requests",
    "staffDashboard.buildingStatus": "Campus Building Status",
    "staffDashboard.viewMonitoring": "View monitoring",
    "staffDashboard.noRequests": "No maintenance requests yet.",
    "staffDashboard.firstRequest": "Submit your first request",
    "staffDashboard.request": "Request",
    "staffDashboard.buildingLocation": "Building / location",
    "staffDashboard.category": "Category",
    "staffDashboard.priority": "Priority",
    "staffDashboard.status": "Status",
    "staffDashboard.created": "Created",
    "staffDashboard.dateUnavailable": "Not available",
    "staffDashboard.action": "Action",
    "staffDashboard.view": "View",
    "staffDashboard.noBuildings": "No buildings available.",
    "staffDashboard.equipment": "equipment",
    "staffDashboard.openRequests": "open requests",
    Electrical: "Electrical",
    "Air Conditioning": "Air Conditioning",
    Plumbing: "Plumbing",
    Lighting: "Lighting",
    Equipment: "Equipment",
    Other: "Other",
    "Unable to connect to the server.": "Unable to connect to the server.",
    "You do not have permission to perform this action.": "You do not have permission to perform this action.",
    "The service is temporarily unavailable. Please try again.": "The service is temporarily unavailable. Please try again.",
    "Something went wrong. Please try again.": "Something went wrong. Please try again.",
    "Unable to complete this action.": "Unable to complete this action.",
  },
  my: {
    "staffDashboard.eyebrow": "တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု",
    "staffDashboard.loading": "ဖွင့်နေသည်…",
    "staffDashboard.retry": "ထပ်မံကြိုးစားရန်",
    "staffDashboard.welcome": "ပြန်လည်ကြိုဆိုပါသည်၊",
    "staffDashboard.description": "သင်၏ ပြုပြင်ထိန်းသိမ်းရေး တင်ပြချက်များနှင့် တက္ကသိုလ်အဆောက်အအုံများ၏ အခြေအနေကို ကြည့်ရှုနိုင်ပါသည်။",
    "staffDashboard.total": "စုစုပေါင်း တင်ပြချက်များ",
    "staffDashboard.pending": "စောင့်ဆိုင်းနေ",
    "staffDashboard.inProgress": "ဆောင်ရွက်နေ",
    "staffDashboard.resolved": "ပြီးစီး",
    "staffDashboard.allSubmissions": "သင်တင်ပြထားသမျှ",
    "staffDashboard.awaiting": "စစ်ဆေးရန် စောင့်ဆိုင်းနေ",
    "staffDashboard.inCare": "ပြုပြင်ဆောင်ရွက်နေ",
    "staffDashboard.completed": "ပြီးစီးသော တင်ပြချက်များ",
    "staffDashboard.prompt": "ပြုပြင်ရန် လိုအပ်နေပါသလား။",
    "staffDashboard.promptHelp": "အဆောက်အအုံဆိုင်ရာ ပြဿနာကို တင်ပြပြီး ဆောင်ရွက်မှုအခြေအနေကို ကြည့်ရှုပါ။",
    "staffDashboard.newMaintenance": "ပြုပြင်ထိန်းသိမ်းရန် တင်ပြချက်အသစ်",
    "staffDashboard.recent": "လတ်တလော တင်ပြချက်များ",
    "staffDashboard.viewAll": "တင်ပြချက်အားလုံး ကြည့်ရန်",
    "staffDashboard.buildingStatus": "တက္ကသိုလ်အဆောက်အအုံ အခြေအနေ",
    "staffDashboard.viewMonitoring": "စောင့်ကြည့်မှု ကြည့်ရန်",
    "staffDashboard.noRequests": "ပြုပြင်ရန် တင်ပြချက် မရှိသေးပါ။",
    "staffDashboard.firstRequest": "ပထမဆုံး တင်ပြချက် တင်သွင်းရန်",
    "staffDashboard.request": "တင်ပြချက်",
    "staffDashboard.buildingLocation": "အဆောက်အအုံ / တည်နေရာ",
    "staffDashboard.category": "အမျိုးအစား",
    "staffDashboard.priority": "ဦးစားပေးအဆင့်",
    "staffDashboard.status": "အခြေအနေ",
    "staffDashboard.created": "တင်ပြသည့်နေ့",
    "staffDashboard.dateUnavailable": "မရနိုင်ပါ",
    "staffDashboard.action": "လုပ်ဆောင်ချက်",
    "staffDashboard.view": "ကြည့်ရန်",
    "staffDashboard.noBuildings": "အဆောက်အအုံ မရှိသေးပါ။",
    "staffDashboard.equipment": "ပစ္စည်းကိရိယာ",
    "staffDashboard.openRequests": "ဆောင်ရွက်ရန် တင်ပြချက်များ",
    Electrical: "လျှပ်စစ်",
    "Air Conditioning": "လေအေးပေးစနစ်",
    Plumbing: "ရေပိုက်စနစ်",
    Lighting: "မီးအလင်းရောင်",
    Equipment: "ပစ္စည်းကိရိယာ",
    Other: "အခြား",
    "Unable to connect to the server.": "ဆာဗာနှင့် ချိတ်ဆက်၍ မရပါ။",
    "You do not have permission to perform this action.": "ဤလုပ်ဆောင်ချက်အတွက် ခွင့်ပြုချက်မရှိပါ။",
    "The service is temporarily unavailable. Please try again.": "ဝန်ဆောင်မှုကို ယာယီအသုံးမပြုနိုင်ပါ။ ထပ်မံကြိုးစားပါ။",
    "Something went wrong. Please try again.": "အမှားတစ်ခု ဖြစ်ပွားခဲ့သည်။ ထပ်မံကြိုးစားပါ။",
    "Unable to complete this action.": "ဤလုပ်ဆောင်ချက်ကို ပြီးမြောက်စေ၍ မရပါ။",
  },
};
const newRequestWords = {
  en: {
    "newRequest.eyebrow": "CAMPUS FACILITIES",
    "newRequest.title": "New maintenance request",
    "newRequest.description": "Tell us what needs attention. Your campus team will take it from here.",
    "newRequest.loading": "Loading…",
    "newRequest.retry": "Try again",
    "newRequest.details": "Request details",
    "newRequest.requiredFields": "* Required fields",
    "newRequest.building": "Building",
    "newRequest.selectBuilding": "Select a building",
    "newRequest.equipment": "Equipment",
    "newRequest.equipmentHint": "Leave unselected for a general building issue.",
    "newRequest.loadingEquipment": "Loading equipment…",
    "newRequest.generalIssue": "No specific equipment / General building issue",
    "newRequest.room": "Room / Location",
    "newRequest.roomPlaceholder": "e.g. Room 205, second floor",
    "newRequest.category": "Fault Category",
    "newRequest.selectCategory": "Select a category",
    "newRequest.descriptionLabel": "Description",
    "newRequest.descriptionHint": "Include what happened and any details that help the facilities team.",
    "newRequest.descriptionPlaceholder": "Describe the issue…",
    "newRequest.priority": "Priority",
    "newRequest.cancel": "Cancel",
    "newRequest.submit": "Submit request",
    "newRequest.saving": "Saving…",
    "newRequest.noteTitle": "A little detail goes a long way",
    "newRequest.noteBuilding": "Choose the correct building and give a clear room or location so the team can find the issue.",
    "newRequest.noteTrack": "You can track updates and administrator notes in My Requests after submitting.",
    "newRequest.blankFields": "Location and description must not be blank.",
    "newRequest.requiredValidation": "Please complete this required field.",
    "newRequest.success": "Maintenance request submitted successfully.",
    "newRequest.refreshError": "Could not refresh the latest data.",
    "Please check the form fields.": "Please check the form fields.",
    "Building not found": "Building not found",
    "Equipment not found": "Equipment not found",
    "Equipment does not belong to the selected building": "Equipment does not belong to the selected building",
  },
  my: {
    "newRequest.eyebrow": "တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု",
    "newRequest.title": "ပြုပြင်ထိန်းသိမ်းရန် တင်ပြချက်အသစ်",
    "newRequest.description": "ပြုပြင်ရန် လိုအပ်သည့်အရာကို ဖော်ပြပါ။ တက္ကသိုလ်အဖွဲ့က ဆက်လက်ဆောင်ရွက်ပါမည်။",
    "newRequest.loading": "ဖွင့်နေသည်…",
    "newRequest.retry": "ထပ်မံကြိုးစားရန်",
    "newRequest.details": "တင်ပြချက် အသေးစိတ်",
    "newRequest.requiredFields": "* မဖြစ်မနေ ဖြည့်ရန်",
    "newRequest.building": "အဆောက်အအုံ",
    "newRequest.selectBuilding": "အဆောက်အအုံ ရွေးချယ်ပါ",
    "newRequest.equipment": "ပစ္စည်းကိရိယာ",
    "newRequest.equipmentHint": "အဆောက်အအုံဆိုင်ရာ အထွေထွေပြဿနာဖြစ်ပါက မရွေးချယ်ဘဲထားပါ။",
    "newRequest.loadingEquipment": "ပစ္စည်းကိရိယာများ ဖွင့်နေသည်…",
    "newRequest.generalIssue": "သီးခြားပစ္စည်း မရှိ / အဆောက်အအုံ အထွေထွေပြဿနာ",
    "newRequest.room": "အခန်း / တည်နေရာ",
    "newRequest.roomPlaceholder": "ဥပမာ - အခန်း ၂၀၅၊ ဒုတိယထပ်",
    "newRequest.category": "ချို့ယွင်းမှု အမျိုးအစား",
    "newRequest.selectCategory": "အမျိုးအစား ရွေးချယ်ပါ",
    "newRequest.descriptionLabel": "ဖော်ပြချက်",
    "newRequest.descriptionHint": "ဖြစ်ပွားခဲ့သည့်အရာနှင့် ပြုပြင်ရေးအဖွဲ့အတွက် အထောက်အကူဖြစ်မည့် အသေးစိတ်ကို ထည့်ပါ။",
    "newRequest.descriptionPlaceholder": "ပြဿနာကို ဖော်ပြပါ…",
    "newRequest.priority": "ဦးစားပေးအဆင့်",
    "newRequest.cancel": "မလုပ်တော့ပါ",
    "newRequest.submit": "တင်ပြချက် တင်သွင်းရန်",
    "newRequest.saving": "သိမ်းဆည်းနေသည်…",
    "newRequest.noteTitle": "အသေးစိတ်ဖော်ပြချက်က အထောက်အကူဖြစ်စေသည်",
    "newRequest.noteBuilding": "မှန်ကန်သော အဆောက်အအုံကို ရွေးပြီး ပြဿနာကို ရှာတွေ့နိုင်ရန် အခန်း သို့မဟုတ် တည်နေရာကို ရှင်းလင်းစွာ ဖော်ပြပါ။",
    "newRequest.noteTrack": "တင်သွင်းပြီးနောက် ကျွန်ုပ်၏ တင်ပြချက်များတွင် ဆောင်ရွက်မှုအခြေအနေနှင့် စီမံခန့်ခွဲသူ၏ မှတ်ချက်များကို ကြည့်နိုင်ပါသည်။",
    "newRequest.blankFields": "တည်နေရာနှင့် ဖော်ပြချက်ကို ကွက်လပ်မထားပါနှင့်။",
    "newRequest.requiredValidation": "မဖြစ်မနေ ဖြည့်ရမည့် ဤအကွက်ကို ဖြည့်ပါ။",
    "newRequest.success": "ပြုပြင်ထိန်းသိမ်းရန် တင်ပြချက်ကို အောင်မြင်စွာ တင်သွင်းပြီးပါပြီ။",
    "newRequest.refreshError": "နောက်ဆုံးအချက်အလက်များကို ပြန်လည်ဖွင့်၍ မရပါ။",
    "Please check the form fields.": "ဖောင်အချက်အလက်များကို စစ်ဆေးပါ။",
    "Building not found": "အဆောက်အအုံကို မတွေ့ပါ။",
    "Equipment not found": "ပစ္စည်းကိရိယာကို မတွေ့ပါ။",
    "Equipment does not belong to the selected building": "ပစ္စည်းကိရိယာသည် ရွေးချယ်ထားသော အဆောက်အအုံတွင် မရှိပါ။",
  },
};
const myRequestsWords = {
  en: {
    "myRequests.eyebrow": "CAMPUS FACILITIES",
    "myRequests.title": "My requests",
    "myRequests.description": "Follow every request, from submission to resolution.",
    "myRequests.newRequest": "New Request",
    "myRequests.filterAria": "Filter requests by status",
    "myRequests.allRequests": "All requests",
    "myRequests.yourRequests": "Your requests",
    "myRequests.oneRequest": "request",
    "myRequests.requestCount": "requests",
    "myRequests.loading": "Loading…",
    "myRequests.retry": "Try again",
    "myRequests.refreshError": "Could not refresh the latest data.",
    "myRequests.noMatches": "No requests match these filters.",
    "myRequests.empty": "No maintenance requests yet.",
    "myRequests.firstRequest": "Submit your first request",
    "myRequests.request": "Request",
    "myRequests.buildingLocation": "Building / location",
    "myRequests.category": "Category",
    "myRequests.priority": "Priority",
    "myRequests.status": "Status",
    "myRequests.created": "Created",
    "myRequests.action": "Action",
    "myRequests.view": "View",
    "myRequests.dateUnavailable": "Not available",
  },
  my: {
    "myRequests.eyebrow": "တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု",
    "myRequests.title": "ကျွန်ုပ်၏ တင်ပြချက်များ",
    "myRequests.description": "တင်သွင်းချိန်မှ ပြီးစီးချိန်အထိ တင်ပြချက်တစ်ခုချင်းစီ၏ အခြေအနေကို ကြည့်ရှုပါ။",
    "myRequests.newRequest": "တင်ပြချက်အသစ်",
    "myRequests.filterAria": "အခြေအနေအလိုက် တင်ပြချက်များ စစ်ထုတ်ရန်",
    "myRequests.allRequests": "တင်ပြချက်အားလုံး",
    "myRequests.yourRequests": "သင်၏ တင်ပြချက်များ",
    "myRequests.oneRequest": "တင်ပြချက်",
    "myRequests.requestCount": "တင်ပြချက်များ",
    "myRequests.loading": "ဖွင့်နေသည်…",
    "myRequests.retry": "ထပ်မံကြိုးစားရန်",
    "myRequests.refreshError": "နောက်ဆုံးအချက်အလက်များကို ပြန်လည်ဖွင့်၍ မရပါ။",
    "myRequests.noMatches": "ဤစစ်ထုတ်မှုနှင့် ကိုက်ညီသော တင်ပြချက် မရှိပါ။",
    "myRequests.empty": "ပြုပြင်ရန် တင်ပြချက် မရှိသေးပါ။",
    "myRequests.firstRequest": "ပထမဆုံး တင်ပြချက် တင်သွင်းရန်",
    "myRequests.request": "တင်ပြချက်",
    "myRequests.buildingLocation": "အဆောက်အအုံ / တည်နေရာ",
    "myRequests.category": "အမျိုးအစား",
    "myRequests.priority": "ဦးစားပေးအဆင့်",
    "myRequests.status": "အခြေအနေ",
    "myRequests.created": "တင်ပြသည့်နေ့",
    "myRequests.action": "လုပ်ဆောင်ချက်",
    "myRequests.view": "ကြည့်ရန်",
    "myRequests.dateUnavailable": "မရနိုင်ပါ",
  },
};
const requestDetailWords = {
  en: {
    "requestDetail.eyebrow": "CAMPUS FACILITIES",
    "requestDetail.back": "Back to requests",
    "requestDetail.request": "Request",
    "requestDetail.description": "Maintenance request details and progress.",
    "requestDetail.loading": "Loading…",
    "requestDetail.retry": "Try again",
    "requestDetail.refreshError": "Could not refresh the latest data.",
    "requestDetail.details": "Request details",
    "requestDetail.building": "Building",
    "requestDetail.room": "Room / Location",
    "requestDetail.equipment": "Equipment",
    "requestDetail.generalIssue": "General building issue",
    "requestDetail.category": "Fault Category",
    "requestDetail.submittedBy": "Submitted By",
    "requestDetail.assignedAdministrator": "Assigned Administrator",
    "requestDetail.unassigned": "Not assigned yet",
    "requestDetail.created": "Created",
    "requestDetail.updated": "Updated",
    "requestDetail.dateUnavailable": "Not available",
    "requestDetail.descriptionLabel": "Description",
    "requestDetail.timeline": "Status timeline",
    "requestDetail.oneEvent": "event",
    "requestDetail.events": "events",
    "requestDetail.submitted": "Request submitted",
    "requestDetail.emptyTimeline": "No status events yet.",
    "Maintenance request not found": "Maintenance request not found",
  },
  my: {
    "requestDetail.eyebrow": "တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု",
    "requestDetail.back": "တင်ပြချက်များသို့ ပြန်သွားရန်",
    "requestDetail.request": "တင်ပြချက်",
    "requestDetail.description": "ပြုပြင်ထိန်းသိမ်းရန် တင်ပြချက်၏ အသေးစိတ်နှင့် ဆောင်ရွက်မှုအခြေအနေ။",
    "requestDetail.loading": "ဖွင့်နေသည်…",
    "requestDetail.retry": "ထပ်မံကြိုးစားရန်",
    "requestDetail.refreshError": "နောက်ဆုံးအချက်အလက်များကို ပြန်လည်ဖွင့်၍ မရပါ။",
    "requestDetail.details": "တင်ပြချက် အသေးစိတ်",
    "requestDetail.building": "အဆောက်အအုံ",
    "requestDetail.room": "အခန်း / တည်နေရာ",
    "requestDetail.equipment": "ပစ္စည်းကိရိယာ",
    "requestDetail.generalIssue": "အဆောက်အအုံဆိုင်ရာ အထွေထွေပြဿနာ",
    "requestDetail.category": "ချို့ယွင်းမှု အမျိုးအစား",
    "requestDetail.submittedBy": "တင်သွင်းသူ",
    "requestDetail.assignedAdministrator": "တာဝန်ပေးထားသော စီမံခန့်ခွဲသူ",
    "requestDetail.unassigned": "တာဝန်မပေးရသေးပါ",
    "requestDetail.created": "တင်သွင်းသည့်နေ့",
    "requestDetail.updated": "နောက်ဆုံးပြင်ဆင်သည့်နေ့",
    "requestDetail.dateUnavailable": "မရနိုင်ပါ",
    "requestDetail.descriptionLabel": "ဖော်ပြချက်",
    "requestDetail.timeline": "အခြေအနေ ပြောင်းလဲမှုမှတ်တမ်း",
    "requestDetail.oneEvent": "ဖြစ်စဉ်",
    "requestDetail.events": "ဖြစ်စဉ်များ",
    "requestDetail.submitted": "တင်ပြချက် တင်သွင်းပြီး",
    "requestDetail.emptyTimeline": "အခြေအနေ ပြောင်းလဲမှုမှတ်တမ်း မရှိသေးပါ။",
    "Maintenance request not found": "ပြုပြင်ထိန်းသိမ်းရန် တင်ပြချက်ကို မတွေ့ပါ။",
  },
};
const adminRequestWords = {
  en: {
    "adminDashboard.eyebrow": "CAMPUS FACILITIES",
    "adminDashboard.title": "Facilities overview",
    "adminDashboard.description": "A clear view of campus operations and what needs your attention.",
    "adminDashboard.manageRequests": "Manage requests",
    "adminDashboard.loading": "Loading…",
    "adminDashboard.retry": "Try again",
    "adminDashboard.refreshError": "Could not refresh the latest data.",
    "adminDashboard.openRequests": "OPEN REQUESTS",
    "adminDashboard.openRequestsNote": "Pending or in progress",
    "adminDashboard.highPriority": "HIGH PRIORITY",
    "adminDashboard.highPriorityNote": "Unresolved high priority",
    "adminDashboard.byStatus": "Requests by status",
    "adminDashboard.byPriority": "Requests by priority",
    "adminDashboard.allRequests": "All requests",
    "adminDashboard.requestsUpper": "REQUESTS",
    "adminDashboard.requests": "Requests",
    "adminDashboard.noChartData": "No requests to chart yet.",
    "adminDashboard.needsAttention": "Needs attention",
    "adminDashboard.needsAttentionDescription": "Unresolved high-priority requests",
    "adminDashboard.viewRequests": "View requests",
    "adminDashboard.assignedTo": "Assigned to",
    "adminDashboard.unassigned": "Not assigned yet",
    "adminDashboard.noAttentionRequests": "No high-priority requests currently require attention.",
    "adminDashboard.buildingOpenRequests": "open requests",
    "adminRequests.eyebrow": "CAMPUS FACILITIES",
    "adminRequests.title": "Request management",
    "adminRequests.description": "Review campus issues, coordinate assignments and track progress.",
    "adminRequests.refreshError": "Could not refresh the latest data.",
    "adminRequests.search": "Search",
    "adminRequests.searchPlaceholder": "Search location, building, equipment or fault…",
    "adminRequests.building": "Building",
    "adminRequests.allBuildings": "All buildings",
    "adminRequests.status": "Status",
    "adminRequests.allStatuses": "All statuses",
    "adminRequests.priority": "Priority",
    "adminRequests.allPriorities": "All priorities",
    "adminRequests.apply": "Apply",
    "adminRequests.clear": "Clear filters",
    "adminRequests.campusRequests": "Campus requests",
    "adminRequests.oneRequest": "request",
    "adminRequests.requestCount": "requests",
    "adminRequests.loading": "Loading…",
    "adminRequests.retry": "Try again",
    "adminRequests.noMatches": "No requests match these filters.",
    "adminRequests.empty": "No maintenance requests yet.",
    "adminRequests.request": "Request",
    "adminRequests.buildingLocation": "Building / location",
    "adminRequests.category": "Category",
    "adminRequests.submittedBy": "Submitted by",
    "adminRequests.assignedTo": "Assigned to",
    "adminRequests.unassigned": "Not assigned yet",
    "adminRequests.created": "Created",
    "adminRequests.action": "Action",
    "adminRequests.manage": "Manage",
    "adminRequests.dateUnavailable": "Not available",
    "adminRequestDetail.eyebrow": "CAMPUS FACILITIES",
    "adminRequestDetail.back": "Back to requests",
    "adminRequestDetail.request": "Request",
    "adminRequestDetail.description": "Maintenance request details and progress.",
    "adminRequestDetail.loading": "Loading…",
    "adminRequestDetail.retry": "Try again",
    "adminRequestDetail.refreshError": "Could not refresh the latest data.",
    "adminRequestDetail.details": "Request details",
    "adminRequestDetail.building": "Building",
    "adminRequestDetail.room": "Room / Location",
    "adminRequestDetail.equipment": "Equipment",
    "adminRequestDetail.generalIssue": "General building issue",
    "adminRequestDetail.category": "Fault Category",
    "adminRequestDetail.submittedBy": "Submitted By",
    "adminRequestDetail.assignedAdministrator": "Assigned Administrator",
    "adminRequestDetail.unassigned": "Not assigned yet",
    "adminRequestDetail.created": "Created",
    "adminRequestDetail.updated": "Updated",
    "adminRequestDetail.dateUnavailable": "Not available",
    "adminRequestDetail.descriptionLabel": "Description",
    "adminRequestDetail.timeline": "Status timeline",
    "adminRequestDetail.oneEvent": "event",
    "adminRequestDetail.events": "events",
    "adminRequestDetail.submitted": "Request submitted",
    "adminRequestDetail.emptyTimeline": "No status events yet.",
    "adminRequestDetail.manage": "Manage request",
    "adminRequestDetail.administrator": "Administrator",
    "adminRequestDetail.assignAdministrator": "Assign administrator",
    "adminRequestDetail.selectAdministrator": "Select administrator",
    "adminRequestDetail.requiredValidation": "Please select an administrator.",
    "adminRequestDetail.updateAssignment": "Update assignment",
    "adminRequestDetail.requestStatus": "Request Status",
    "adminRequestDetail.optionalNote": "Optional Note",
    "adminRequestDetail.notePlaceholder": "Add a progress update…",
    "adminRequestDetail.updateStatus": "Update status",
    "adminRequestDetail.saving": "Saving…",
    "adminRequestDetail.assignmentSuccess": "Request assignment updated.",
    "adminRequestDetail.statusSuccess": "Request status updated.",
    "Assignee not found": "Assignee not found",
    "Assignee must be an administrator": "Assignee must be an administrator",
  },
  my: {
    "adminDashboard.eyebrow": "တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု",
    "adminDashboard.title": "အဆောက်အအုံဝန်ဆောင်မှု အနှစ်ချုပ်",
    "adminDashboard.description": "တက္ကသိုလ်လုပ်ငန်းအခြေအနေနှင့် စစ်ဆေးရန်လိုအပ်သည့်အရာများကို တစ်နေရာတည်းတွင် ကြည့်ရှုပါ။",
    "adminDashboard.manageRequests": "တင်ပြချက်များ စီမံရန်",
    "adminDashboard.loading": "ဖွင့်နေသည်…",
    "adminDashboard.retry": "ထပ်မံကြိုးစားရန်",
    "adminDashboard.refreshError": "နောက်ဆုံးအချက်အလက်များကို ပြန်လည်ဖွင့်၍ မရပါ။",
    "adminDashboard.openRequests": "ဆောင်ရွက်ဆဲ တင်ပြချက်များ",
    "adminDashboard.openRequestsNote": "စောင့်ဆိုင်းနေ သို့မဟုတ် ဆောင်ရွက်နေ",
    "adminDashboard.highPriority": "ဦးစားပေးအဆင့် မြင့်",
    "adminDashboard.highPriorityNote": "မပြီးစီးသေးသော ဦးစားပေးအဆင့်မြင့် တင်ပြချက်များ",
    "adminDashboard.byStatus": "အခြေအနေအလိုက် တင်ပြချက်များ",
    "adminDashboard.byPriority": "ဦးစားပေးအဆင့်အလိုက် တင်ပြချက်များ",
    "adminDashboard.allRequests": "တင်ပြချက်အားလုံး",
    "adminDashboard.requestsUpper": "တင်ပြချက်များ",
    "adminDashboard.requests": "တင်ပြချက်များ",
    "adminDashboard.noChartData": "ဇယားပြရန် တင်ပြချက် မရှိသေးပါ။",
    "adminDashboard.needsAttention": "စစ်ဆေးရန် လိုအပ်သည်များ",
    "adminDashboard.needsAttentionDescription": "မပြီးစီးသေးသော ဦးစားပေးအဆင့်မြင့် တင်ပြချက်များ",
    "adminDashboard.viewRequests": "တင်ပြချက်များ ကြည့်ရန်",
    "adminDashboard.assignedTo": "တာဝန်ပေးထားသူ",
    "adminDashboard.unassigned": "တာဝန်မပေးရသေးပါ",
    "adminDashboard.noAttentionRequests": "လက်ရှိ စစ်ဆေးရန်လိုအပ်သော ဦးစားပေးအဆင့်မြင့် တင်ပြချက် မရှိပါ။",
    "adminDashboard.buildingOpenRequests": "ဆောင်ရွက်ရန် တင်ပြချက်များ",
    "adminRequests.eyebrow": "တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု",
    "adminRequests.title": "တင်ပြချက် စီမံခန့်ခွဲမှု",
    "adminRequests.description": "တက္ကသိုလ်ပြဿနာများကို စစ်ဆေး၍ တာဝန်ခွဲဝေပြီး ဆောင်ရွက်မှုအခြေအနေကို ကြည့်ရှုပါ။",
    "adminRequests.refreshError": "နောက်ဆုံးအချက်အလက်များကို ပြန်လည်ဖွင့်၍ မရပါ။",
    "adminRequests.search": "ရှာဖွေရန်",
    "adminRequests.searchPlaceholder": "တည်နေရာ၊ အဆောက်အအုံ၊ ပစ္စည်းကိရိယာ သို့မဟုတ် ချို့ယွင်းမှုကို ရှာရန်…",
    "adminRequests.building": "အဆောက်အအုံ",
    "adminRequests.allBuildings": "အဆောက်အအုံအားလုံး",
    "adminRequests.status": "အခြေအနေ",
    "adminRequests.allStatuses": "အခြေအနေအားလုံး",
    "adminRequests.priority": "ဦးစားပေးအဆင့်",
    "adminRequests.allPriorities": "ဦးစားပေးအဆင့်အားလုံး",
    "adminRequests.apply": "စစ်ထုတ်ရန်",
    "adminRequests.clear": "စစ်ထုတ်မှုများ ရှင်းရန်",
    "adminRequests.campusRequests": "တက္ကသိုလ် တင်ပြချက်များ",
    "adminRequests.oneRequest": "တင်ပြချက်",
    "adminRequests.requestCount": "တင်ပြချက်များ",
    "adminRequests.loading": "ဖွင့်နေသည်…",
    "adminRequests.retry": "ထပ်မံကြိုးစားရန်",
    "adminRequests.noMatches": "ဤစစ်ထုတ်မှုများနှင့် ကိုက်ညီသော တင်ပြချက် မရှိပါ။",
    "adminRequests.empty": "ပြုပြင်ရန် တင်ပြချက် မရှိသေးပါ။",
    "adminRequests.request": "တင်ပြချက်",
    "adminRequests.buildingLocation": "အဆောက်အအုံ / တည်နေရာ",
    "adminRequests.category": "အမျိုးအစား",
    "adminRequests.submittedBy": "တင်သွင်းသူ",
    "adminRequests.assignedTo": "တာဝန်ပေးထားသူ",
    "adminRequests.unassigned": "တာဝန်မပေးရသေးပါ",
    "adminRequests.created": "တင်သွင်းသည့်နေ့",
    "adminRequests.action": "လုပ်ဆောင်ချက်",
    "adminRequests.manage": "စီမံရန်",
    "adminRequests.dateUnavailable": "မရနိုင်ပါ",
    "adminRequestDetail.eyebrow": "တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု",
    "adminRequestDetail.back": "တင်ပြချက်များသို့ ပြန်သွားရန်",
    "adminRequestDetail.request": "တင်ပြချက်",
    "adminRequestDetail.description": "ပြုပြင်ထိန်းသိမ်းရန် တင်ပြချက်၏ အသေးစိတ်နှင့် ဆောင်ရွက်မှုအခြေအနေ။",
    "adminRequestDetail.loading": "ဖွင့်နေသည်…",
    "adminRequestDetail.retry": "ထပ်မံကြိုးစားရန်",
    "adminRequestDetail.refreshError": "နောက်ဆုံးအချက်အလက်များကို ပြန်လည်ဖွင့်၍ မရပါ။",
    "adminRequestDetail.details": "တင်ပြချက် အသေးစိတ်",
    "adminRequestDetail.building": "အဆောက်အအုံ",
    "adminRequestDetail.room": "အခန်း / တည်နေရာ",
    "adminRequestDetail.equipment": "ပစ္စည်းကိရိယာ",
    "adminRequestDetail.generalIssue": "အဆောက်အအုံဆိုင်ရာ အထွေထွေပြဿနာ",
    "adminRequestDetail.category": "ချို့ယွင်းမှု အမျိုးအစား",
    "adminRequestDetail.submittedBy": "တင်သွင်းသူ",
    "adminRequestDetail.assignedAdministrator": "တာဝန်ပေးထားသော စီမံခန့်ခွဲသူ",
    "adminRequestDetail.unassigned": "တာဝန်မပေးရသေးပါ",
    "adminRequestDetail.created": "တင်သွင်းသည့်နေ့",
    "adminRequestDetail.updated": "နောက်ဆုံးပြင်ဆင်သည့်နေ့",
    "adminRequestDetail.dateUnavailable": "မရနိုင်ပါ",
    "adminRequestDetail.descriptionLabel": "ဖော်ပြချက်",
    "adminRequestDetail.timeline": "အခြေအနေ ပြောင်းလဲမှုမှတ်တမ်း",
    "adminRequestDetail.oneEvent": "ဖြစ်စဉ်",
    "adminRequestDetail.events": "ဖြစ်စဉ်များ",
    "adminRequestDetail.submitted": "တင်ပြချက် တင်သွင်းပြီး",
    "adminRequestDetail.emptyTimeline": "အခြေအနေ ပြောင်းလဲမှုမှတ်တမ်း မရှိသေးပါ။",
    "adminRequestDetail.manage": "တင်ပြချက် စီမံရန်",
    "adminRequestDetail.administrator": "စီမံခန့်ခွဲသူ",
    "adminRequestDetail.assignAdministrator": "စီမံခန့်ခွဲသူ တာဝန်ပေးရန်",
    "adminRequestDetail.selectAdministrator": "စီမံခန့်ခွဲသူ ရွေးချယ်ပါ",
    "adminRequestDetail.requiredValidation": "စီမံခန့်ခွဲသူတစ်ဦး ရွေးချယ်ပါ။",
    "adminRequestDetail.updateAssignment": "တာဝန်ပေးမှု ပြင်ဆင်ရန်",
    "adminRequestDetail.requestStatus": "တင်ပြချက် အခြေအနေ",
    "adminRequestDetail.optionalNote": "မှတ်ချက် (မဖြစ်မနေ မဟုတ်ပါ)",
    "adminRequestDetail.notePlaceholder": "ဆောင်ရွက်မှုအခြေအနေ အသစ်ထည့်ရန်…",
    "adminRequestDetail.updateStatus": "အခြေအနေ ပြင်ဆင်ရန်",
    "adminRequestDetail.saving": "သိမ်းဆည်းနေသည်…",
    "adminRequestDetail.assignmentSuccess": "တင်ပြချက် တာဝန်ပေးမှုကို ပြင်ဆင်ပြီးပါပြီ။",
    "adminRequestDetail.statusSuccess": "တင်ပြချက် အခြေအနေကို ပြင်ဆင်ပြီးပါပြီ။",
    "Assignee not found": "တာဝန်ပေးမည့်သူကို မတွေ့ပါ။",
    "Assignee must be an administrator": "တာဝန်ပေးမည့်သူသည် စီမံခန့်ခွဲသူ ဖြစ်ရပါမည်။",
  },
};
const equipmentMaintenanceWords = {
  en: {
    "equipmentPage.eyebrow": "CAMPUS FACILITIES",
    "equipmentPage.title": "Equipment management",
    "equipmentPage.description": "Keep campus equipment records accurate and up to date.",
    "equipmentPage.add": "Add Equipment",
    "equipmentPage.search": "Search equipment",
    "equipmentPage.searchPlaceholder": "Name, type, location or building…",
    "equipmentPage.building": "Building",
    "equipmentPage.allBuildings": "All buildings",
    "equipmentPage.status": "Status",
    "equipmentPage.allStatuses": "All statuses",
    "equipmentPage.clear": "Clear filters",
    "equipmentPage.retry": "Try again",
    "equipmentPage.refreshError": "Could not refresh the latest data.",
    "equipmentPage.campusEquipment": "Campus equipment",
    "equipmentPage.oneRecord": "record",
    "equipmentPage.records": "records",
    "equipmentPage.loading": "Loading…",
    "equipmentPage.equipment": "Equipment",
    "equipmentPage.type": "Type",
    "equipmentPage.equipmentType": "Equipment Type",
    "equipmentPage.location": "Location",
    "equipmentPage.action": "Action",
    "equipmentPage.edit": "Edit",
    "equipmentPage.editEquipment": "Edit equipment",
    "equipmentPage.empty": "No equipment matches the selected filters.",
    "equipmentPage.editDialog": "Edit equipment",
    "equipmentPage.addDialog": "Add equipment",
    "equipmentPage.closeDialog": "Close equipment dialog",
    "equipmentPage.requiredFields": "Please complete all required fields.",
    "equipmentPage.requiredValidation": "Please complete this required field.",
    "equipmentPage.updateSuccess": "Equipment updated successfully.",
    "equipmentPage.addSuccess": "Equipment added successfully.",
    "equipmentPage.selectBuilding": "Select a building",
    "equipmentPage.name": "Equipment Name",
    "equipmentPage.save": "Save changes",
    "equipmentPage.addButton": "Add equipment",
    "equipmentPage.saving": "Saving…",
    "maintenancePage.eyebrow": "CAMPUS FACILITIES",
    "maintenancePage.title": "Maintenance history",
    "maintenancePage.description": "A record of completed equipment work across campus.",
    "maintenancePage.record": "Record Maintenance",
    "maintenancePage.building": "Building",
    "maintenancePage.allBuildings": "All buildings",
    "maintenancePage.equipment": "Equipment",
    "maintenancePage.allEquipment": "All equipment",
    "maintenancePage.clear": "Clear filters",
    "maintenancePage.retry": "Try again",
    "maintenancePage.refreshError": "Could not refresh the latest data.",
    "maintenancePage.completedMaintenance": "Completed maintenance",
    "maintenancePage.oneRecord": "record",
    "maintenancePage.records": "records",
    "maintenancePage.loading": "Loading…",
    "maintenancePage.completed": "Completed",
    "maintenancePage.equipmentBuilding": "Equipment / building",
    "maintenancePage.linkedRequest": "Linked request",
    "maintenancePage.completedBy": "Completed by",
    "maintenancePage.actionDetails": "Action Details",
    "maintenancePage.request": "Request",
    "maintenancePage.preventive": "Preventive maintenance",
    "maintenancePage.dateUnavailable": "Not available",
    "maintenancePage.empty": "No maintenance records found.",
    "maintenancePage.recordDialog": "Record maintenance",
    "maintenancePage.closeDialog": "Close maintenance dialog",
    "maintenancePage.dialogIntro": "Record completed work. Linked requests must already be resolved.",
    "maintenancePage.detailsRequired": "Please describe the maintenance completed.",
    "maintenancePage.requiredValidation": "Please complete this required field.",
    "maintenancePage.createSuccess": "Maintenance record created.",
    "maintenancePage.selectEquipment": "Select equipment",
    "maintenancePage.linkedResolvedRequest": "Linked Resolved Request",
    "maintenancePage.noResolvedRequests": "No resolved requests are available for this equipment.",
    "maintenancePage.loadingRequests": "Loading resolved requests…",
    "maintenancePage.noLinkedRequest": "No linked request — Preventive maintenance",
    "maintenancePage.detailsPlaceholder": "Describe the work completed…",
    "maintenancePage.saving": "Saving…",
    "maintenancePage.recordButton": "Record maintenance",
    "Maintenance request does not belong to the selected equipment": "Maintenance request does not belong to the selected equipment",
    "Maintenance request must be resolved before recording completed maintenance": "Maintenance request must be resolved before recording completed maintenance",
  },
  my: {
    "equipmentPage.eyebrow": "တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု",
    "equipmentPage.title": "ပစ္စည်းကိရိယာ စီမံခန့်ခွဲမှု",
    "equipmentPage.description": "တက္ကသိုလ်ပစ္စည်းကိရိယာ မှတ်တမ်းများကို မှန်ကန်ပြီး နောက်ဆုံးအခြေအနေဖြစ်အောင် ထိန်းသိမ်းပါ။",
    "equipmentPage.add": "ပစ္စည်းကိရိယာ ထည့်ရန်",
    "equipmentPage.search": "ပစ္စည်းကိရိယာ ရှာရန်",
    "equipmentPage.searchPlaceholder": "အမည်၊ အမျိုးအစား၊ တည်နေရာ သို့မဟုတ် အဆောက်အအုံ…",
    "equipmentPage.building": "အဆောက်အအုံ",
    "equipmentPage.allBuildings": "အဆောက်အအုံအားလုံး",
    "equipmentPage.status": "အခြေအနေ",
    "equipmentPage.allStatuses": "အခြေအနေအားလုံး",
    "equipmentPage.clear": "စစ်ထုတ်မှုများ ရှင်းရန်",
    "equipmentPage.retry": "ထပ်မံကြိုးစားရန်",
    "equipmentPage.refreshError": "နောက်ဆုံးအချက်အလက်များကို ပြန်လည်ဖွင့်၍ မရပါ။",
    "equipmentPage.campusEquipment": "တက္ကသိုလ် ပစ္စည်းကိရိယာများ",
    "equipmentPage.oneRecord": "မှတ်တမ်း",
    "equipmentPage.records": "မှတ်တမ်းများ",
    "equipmentPage.loading": "ဖွင့်နေသည်…",
    "equipmentPage.equipment": "ပစ္စည်းကိရိယာ",
    "equipmentPage.type": "အမျိုးအစား",
    "equipmentPage.equipmentType": "ပစ္စည်းကိရိယာ အမျိုးအစား",
    "equipmentPage.location": "တည်နေရာ",
    "equipmentPage.action": "လုပ်ဆောင်ချက်",
    "equipmentPage.edit": "ပြင်ဆင်ရန်",
    "equipmentPage.editEquipment": "ပစ္စည်းကိရိယာ ပြင်ဆင်ရန်",
    "equipmentPage.empty": "ရွေးချယ်ထားသော စစ်ထုတ်မှုများနှင့် ကိုက်ညီသည့် ပစ္စည်းကိရိယာ မရှိပါ။",
    "equipmentPage.editDialog": "ပစ္စည်းကိရိယာ ပြင်ဆင်ရန်",
    "equipmentPage.addDialog": "ပစ္စည်းကိရိယာ ထည့်ရန်",
    "equipmentPage.closeDialog": "ပစ္စည်းကိရိယာ ဖောင်ကို ပိတ်ရန်",
    "equipmentPage.requiredFields": "မဖြစ်မနေ ဖြည့်ရမည့် အကွက်အားလုံးကို ဖြည့်ပါ။",
    "equipmentPage.requiredValidation": "မဖြစ်မနေ ဖြည့်ရမည့် ဤအကွက်ကို ဖြည့်ပါ။",
    "equipmentPage.updateSuccess": "ပစ္စည်းကိရိယာကို အောင်မြင်စွာ ပြင်ဆင်ပြီးပါပြီ။",
    "equipmentPage.addSuccess": "ပစ္စည်းကိရိယာကို အောင်မြင်စွာ ထည့်ပြီးပါပြီ။",
    "equipmentPage.selectBuilding": "အဆောက်အအုံ ရွေးချယ်ပါ",
    "equipmentPage.name": "ပစ္စည်းကိရိယာ အမည်",
    "equipmentPage.save": "ပြင်ဆင်ချက်များ သိမ်းရန်",
    "equipmentPage.addButton": "ပစ္စည်းကိရိယာ ထည့်ရန်",
    "equipmentPage.saving": "သိမ်းဆည်းနေသည်…",
    "maintenancePage.eyebrow": "တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု",
    "maintenancePage.title": "ပြုပြင်ထိန်းသိမ်းမှု မှတ်တမ်း",
    "maintenancePage.description": "တက္ကသိုလ်အတွင်း ပြီးစီးခဲ့သော ပစ္စည်းကိရိယာ ပြုပြင်မှုမှတ်တမ်းများ။",
    "maintenancePage.record": "ပြုပြင်မှု မှတ်တမ်းတင်ရန်",
    "maintenancePage.building": "အဆောက်အအုံ",
    "maintenancePage.allBuildings": "အဆောက်အအုံအားလုံး",
    "maintenancePage.equipment": "ပစ္စည်းကိရိယာ",
    "maintenancePage.allEquipment": "ပစ္စည်းကိရိယာအားလုံး",
    "maintenancePage.clear": "စစ်ထုတ်မှုများ ရှင်းရန်",
    "maintenancePage.retry": "ထပ်မံကြိုးစားရန်",
    "maintenancePage.refreshError": "နောက်ဆုံးအချက်အလက်များကို ပြန်လည်ဖွင့်၍ မရပါ။",
    "maintenancePage.completedMaintenance": "ပြီးစီးသော ပြုပြင်ထိန်းသိမ်းမှုများ",
    "maintenancePage.oneRecord": "မှတ်တမ်း",
    "maintenancePage.records": "မှတ်တမ်းများ",
    "maintenancePage.loading": "ဖွင့်နေသည်…",
    "maintenancePage.completed": "ပြီးစီးသည့်နေ့",
    "maintenancePage.equipmentBuilding": "ပစ္စည်းကိရိယာ / အဆောက်အအုံ",
    "maintenancePage.linkedRequest": "ချိတ်ဆက်ထားသော တင်ပြချက်",
    "maintenancePage.completedBy": "ပြီးစီးအောင် ဆောင်ရွက်သူ",
    "maintenancePage.actionDetails": "ဆောင်ရွက်မှု အသေးစိတ်",
    "maintenancePage.request": "တင်ပြချက်",
    "maintenancePage.preventive": "ကြိုတင်ကာကွယ် ပြုပြင်ထိန်းသိမ်းမှု",
    "maintenancePage.dateUnavailable": "မရနိုင်ပါ",
    "maintenancePage.empty": "ပြုပြင်ထိန်းသိမ်းမှု မှတ်တမ်း မရှိပါ။",
    "maintenancePage.recordDialog": "ပြုပြင်ထိန်းသိမ်းမှု မှတ်တမ်းတင်ရန်",
    "maintenancePage.closeDialog": "ပြုပြင်ထိန်းသိမ်းမှု ဖောင်ကို ပိတ်ရန်",
    "maintenancePage.dialogIntro": "ပြီးစီးသော လုပ်ငန်းကို မှတ်တမ်းတင်ပါ။ ချိတ်ဆက်မည့် တင်ပြချက်သည် ပြီးစီးထားပြီး ဖြစ်ရပါမည်။",
    "maintenancePage.detailsRequired": "ပြီးစီးခဲ့သော ပြုပြင်ထိန်းသိမ်းမှုကို ဖော်ပြပါ။",
    "maintenancePage.requiredValidation": "မဖြစ်မနေ ဖြည့်ရမည့် ဤအကွက်ကို ဖြည့်ပါ။",
    "maintenancePage.createSuccess": "ပြုပြင်ထိန်းသိမ်းမှု မှတ်တမ်းကို ဖန်တီးပြီးပါပြီ။",
    "maintenancePage.selectEquipment": "ပစ္စည်းကိရိယာ ရွေးချယ်ပါ",
    "maintenancePage.linkedResolvedRequest": "ချိတ်ဆက်မည့် ပြီးစီးထားသော တင်ပြချက်",
    "maintenancePage.noResolvedRequests": "ဤပစ္စည်းကိရိယာအတွက် ပြီးစီးထားသော တင်ပြချက် မရှိပါ။",
    "maintenancePage.loadingRequests": "ပြီးစီးထားသော တင်ပြချက်များ ဖွင့်နေသည်…",
    "maintenancePage.noLinkedRequest": "ချိတ်ဆက်ထားသော တင်ပြချက် မရှိ — ကြိုတင်ကာကွယ် ပြုပြင်မှု",
    "maintenancePage.detailsPlaceholder": "ပြီးစီးခဲ့သော လုပ်ငန်းကို ဖော်ပြပါ…",
    "maintenancePage.saving": "သိမ်းဆည်းနေသည်…",
    "maintenancePage.recordButton": "ပြုပြင်မှု မှတ်တမ်းတင်ရန်",
    "Maintenance request does not belong to the selected equipment": "ပြုပြင်ထိန်းသိမ်းရန် တင်ပြချက်သည် ရွေးချယ်ထားသော ပစ္စည်းကိရိယာနှင့် မသက်ဆိုင်ပါ။",
    "Maintenance request must be resolved before recording completed maintenance": "ပြီးစီးသော ပြုပြင်မှုကို မှတ်တမ်းမတင်မီ တင်ပြချက်ကို ပြီးစီးထားရပါမည်။",
  },
};
const monitoringWords = {
  en: {
    "monitoringPage.eyebrow": "SMART CAMPUS MONITORING",
    "monitoringPage.title": "Building monitoring",
    "monitoringPage.description": "Real-time-style overview using simulated environmental data.",
    "monitoringPage.refresh": "Refresh",
    "monitoringPage.refreshError": "Could not refresh the latest data.",
    "monitoringPage.simulatedData": "Simulated Environmental Data",
    "monitoringPage.readOnly": "Read-only campus overview",
    "monitoringPage.loading": "Loading…",
    "monitoringPage.loadingHistory": "Loading environmental history…",
    "monitoringPage.retry": "Try again",
    "monitoringPage.noBuildings": "No buildings available.",
    "monitoringPage.temperature": "Temperature",
    "monitoringPage.humidity": "Humidity",
    "monitoringPage.humidityLower": "humidity",
    "monitoringPage.energy": "Energy",
    "monitoringPage.equipmentLower": "equipment",
    "monitoringPage.openRequests": "open requests",
    "monitoringPage.equipment": "Equipment",
    "monitoringPage.requests": "Requests",
    "monitoringPage.operational": "operational",
    "monitoringPage.maintenanceRequired": "maintenance required",
    "monitoringPage.outOfService": "out of service",
    "monitoringPage.pending": "pending",
    "monitoringPage.inProgress": "in progress",
    "monitoringPage.resolved": "resolved",
    "monitoringPage.reading": "Reading",
    "monitoringPage.noReadings": "No environmental readings available",
    "monitoringPage.closeDialog": "Close building monitoring dialog",
    "monitoringPage.latestReading": "Latest reading",
    "monitoringPage.noBuildingReadings": "No environmental readings are available for this building.",
    "monitoringPage.temperatureHumidity": "Temperature & humidity",
    "monitoringPage.temperatureHumidityAria": "Temperature and humidity readings over time. The chart legend identifies both lines.",
    "monitoringPage.temperatureSeries": "Temperature (°C)",
    "monitoringPage.humiditySeries": "Humidity (%)",
    "monitoringPage.energyConsumption": "Energy consumption",
    "monitoringPage.energyAria": "Energy consumption readings over time. The chart legend identifies the line.",
    "monitoringPage.energySeries": "Energy (kWh)",
    "monitoringPage.environmentalHistory": "Environmental history",
    "monitoringPage.oneReading": "reading",
    "monitoringPage.readings": "readings",
    "monitoringPage.environmentalReadings": "Environmental readings",
    "monitoringPage.recorded": "Recorded",
    "adminDashboard.equipmentAttention": "EQUIPMENT ATTENTION",
    "adminDashboard.equipmentAttentionNote": "Maintenance or out of service",
    "adminDashboard.staffAccounts": "STAFF ACCOUNTS",
    "adminDashboard.staffAccountsNote": "Office Staff with access",
    "adminDashboard.buildingStatus": "Campus Building Status",
    "adminDashboard.viewMonitoring": "View monitoring",
    "adminDashboard.noBuildings": "No buildings available.",
    "adminDashboard.buildingEquipment": "equipment",
  },
  my: {
    "monitoringPage.eyebrow": "စမတ်တက္ကသိုလ် စောင့်ကြည့်မှု",
    "monitoringPage.title": "အဆောက်အအုံ စောင့်ကြည့်မှု",
    "monitoringPage.description": "သရုပ်ပြ ပတ်ဝန်းကျင်အချက်အလက်များဖြင့် လက်ရှိအခြေအနေကဲ့သို့ ကြည့်ရှုနိုင်ပါသည်။",
    "monitoringPage.refresh": "ပြန်လည်ဖွင့်ရန်",
    "monitoringPage.refreshError": "နောက်ဆုံးအချက်အလက်များကို ပြန်လည်ဖွင့်၍ မရပါ။",
    "monitoringPage.simulatedData": "သရုပ်ပြ ပတ်ဝန်းကျင်အချက်အလက်",
    "monitoringPage.readOnly": "ကြည့်ရှုရန်သာ တက္ကသိုလ်အနှစ်ချုပ်",
    "monitoringPage.loading": "ဖွင့်နေသည်…",
    "monitoringPage.loadingHistory": "ပတ်ဝန်းကျင်အချက်အလက်မှတ်တမ်း ဖွင့်နေသည်…",
    "monitoringPage.retry": "ထပ်မံကြိုးစားရန်",
    "monitoringPage.noBuildings": "အဆောက်အအုံ မရှိသေးပါ။",
    "monitoringPage.temperature": "အပူချိန်",
    "monitoringPage.humidity": "စိုထိုင်းဆ",
    "monitoringPage.humidityLower": "စိုထိုင်းဆ",
    "monitoringPage.energy": "စွမ်းအင်",
    "monitoringPage.equipmentLower": "ပစ္စည်းကိရိယာ",
    "monitoringPage.openRequests": "ဆောင်ရွက်ရန် တင်ပြချက်များ",
    "monitoringPage.equipment": "ပစ္စည်းကိရိယာ",
    "monitoringPage.requests": "တင်ပြချက်များ",
    "monitoringPage.operational": "အသုံးပြုနိုင်",
    "monitoringPage.maintenanceRequired": "ပြုပြင်ရန်လို",
    "monitoringPage.outOfService": "အသုံးမပြုနိုင်",
    "monitoringPage.pending": "စောင့်ဆိုင်းနေ",
    "monitoringPage.inProgress": "ဆောင်ရွက်နေ",
    "monitoringPage.resolved": "ပြီးစီး",
    "monitoringPage.reading": "တိုင်းတာချက်",
    "monitoringPage.noReadings": "ပတ်ဝန်းကျင် တိုင်းတာချက် မရှိသေးပါ",
    "monitoringPage.closeDialog": "အဆောက်အအုံ စောင့်ကြည့်မှုဖောင်ကို ပိတ်ရန်",
    "monitoringPage.latestReading": "နောက်ဆုံး တိုင်းတာချက်",
    "monitoringPage.noBuildingReadings": "ဤအဆောက်အအုံအတွက် ပတ်ဝန်းကျင် တိုင်းတာချက် မရှိသေးပါ။",
    "monitoringPage.temperatureHumidity": "အပူချိန်နှင့် စိုထိုင်းဆ",
    "monitoringPage.temperatureHumidityAria": "အချိန်အလိုက် အပူချိန်နှင့် စိုထိုင်းဆ တိုင်းတာချက်ဇယား။ ဇယားညွှန်းတွင် လိုင်းနှစ်ခုကို ဖော်ပြထားသည်။",
    "monitoringPage.temperatureSeries": "အပူချိန် (°C)",
    "monitoringPage.humiditySeries": "စိုထိုင်းဆ (%)",
    "monitoringPage.energyConsumption": "စွမ်းအင် သုံးစွဲမှု",
    "monitoringPage.energyAria": "အချိန်အလိုက် စွမ်းအင်သုံးစွဲမှု တိုင်းတာချက်ဇယား။ ဇယားညွှန်းတွင် လိုင်းကို ဖော်ပြထားသည်။",
    "monitoringPage.energySeries": "စွမ်းအင် (kWh)",
    "monitoringPage.environmentalHistory": "ပတ်ဝန်းကျင် တိုင်းတာချက်မှတ်တမ်း",
    "monitoringPage.oneReading": "တိုင်းတာချက်",
    "monitoringPage.readings": "တိုင်းတာချက်များ",
    "monitoringPage.environmentalReadings": "ပတ်ဝန်းကျင် တိုင်းတာချက်များ",
    "monitoringPage.recorded": "မှတ်တမ်းတင်ချိန်",
    "adminDashboard.equipmentAttention": "စစ်ဆေးရန်လိုသော ပစ္စည်းကိရိယာ",
    "adminDashboard.equipmentAttentionNote": "ပြုပြင်ရန်လို သို့မဟုတ် အသုံးမပြုနိုင်",
    "adminDashboard.staffAccounts": "ဝန်ထမ်းအကောင့်များ",
    "adminDashboard.staffAccountsNote": "အသုံးပြုခွင့်ရှိသော ရုံးဝန်ထမ်းများ",
    "adminDashboard.buildingStatus": "တက္ကသိုလ်အဆောက်အအုံ အခြေအနေ",
    "adminDashboard.viewMonitoring": "စောင့်ကြည့်မှု ကြည့်ရန်",
    "adminDashboard.noBuildings": "အဆောက်အအုံ မရှိသေးပါ။",
    "adminDashboard.buildingEquipment": "ပစ္စည်းကိရိယာ",
  },
};
const finalLocalizationWords = {
  en: {
    "staffAccountsPage.eyebrow": "CAMPUS FACILITIES",
    "staffAccountsPage.title": "Staff accounts",
    "staffAccountsPage.description": "Manage Office Staff access to the Smart Building Monitoring System.",
    "staffAccountsPage.create": "Create Staff Account",
    "staffAccountsPage.officeStaff": "Office Staff",
    "staffAccountsPage.oneAccount": "account",
    "staffAccountsPage.accounts": "accounts",
    "staffAccountsPage.loading": "Loading…",
    "staffAccountsPage.retry": "Try again",
    "staffAccountsPage.refreshError": "Could not refresh the latest data.",
    "staffAccountsPage.facilitiesAccess": "Campus facilities access",
    "staffAccountsPage.empty": "No Staff accounts yet.",
    "staffAccountsPage.accessNote": "New accounts receive Office Staff access.",
    "staffAccountsPage.nameRequired": "Please enter a name.",
    "staffAccountsPage.passwordMismatch": "Passwords must match.",
    "staffAccountsPage.createSuccess": "Staff account created successfully.",
    "staffAccountsPage.createDialog": "Create Staff account",
    "staffAccountsPage.closeDialog": "Close Staff account dialog",
    "staffAccountsPage.dialogIntro": "Create access for a member of Office Staff.",
    "staffAccountsPage.requiredValidation": "Please complete this required field.",
    "staffAccountsPage.name": "Name",
    "staffAccountsPage.initialPassword": "Initial Password",
    "staffAccountsPage.passwordHint": "Use at least 8 characters.",
    "staffAccountsPage.confirmPassword": "Confirm Password",
    "staffAccountsPage.saving": "Saving…",
    "A user with this name already exists": "A user with this name already exists",
    "Invalid login credentials or role": "Invalid login credentials or role",
    "shell.smartBuilding": "Smart Building",
    "shell.monitoringSystem": "Monitoring System",
    "shell.smartCampusFacilities": "SMART CAMPUS FACILITIES",
    "shell.campusManagement": "CAMPUS MANAGEMENT",
    "shell.myWorkspace": "MY WORKSPACE",
    "shell.mainNavigation": "Main navigation",
    "shell.campusFoot": "Smart Campus · CET333",
    "shell.navigation": "Navigation",
    "shell.closeMenu": "Close menu",
    "shell.openMenu": "Open menu",
    "shell.smartCampus": "Smart Campus",
    "shell.campusFacilities": "Campus Facilities",
    "shell.footerTitle": "Smart Building Monitoring System",
    "shell.footerTagline": "Campus facilities, connected.",
    "login.sessionCheckUnavailable": "SESSION CHECK UNAVAILABLE",
    "login.sessionUnavailableTitle": "Unable to verify your session right now.",
    "login.sessionUnavailableDescription": "Your saved session is still protected. Try again when the service is available.",
    "login.retrySession": "Retry session check",
    "login.nameRequired": "Please enter your name.",
    "login.monitoringSystem": "MONITORING SYSTEM",
    "login.portalLabel": "SMART CAMPUS FACILITIES PORTAL",
    "login.monitoring": "Monitoring.",
    "login.titleNote": "A more connected campus.",
    "login.story": "Monitor campus buildings, manage maintenance requests and keep facilities running smoothly.",
    "login.campusMonitoring": "Campus Monitoring",
    "login.maintenanceManagement": "Maintenance Management",
    "login.secureAccess": "Secure Role-Based Access",
    "login.welcome": "WELCOME TO YOUR WORKSPACE",
    "login.signIn": "Sign in",
    "login.accessPortal": "Access your campus facilities portal.",
    "login.requiredValidation": "Please complete this required field.",
    "login.name": "Name",
    "login.namePlaceholder": "Enter your name",
    "login.password": "Password",
    "login.passwordPlaceholder": "Enter your password",
    "login.showPassword": "Show password",
    "login.hidePassword": "Hide password",
    "login.signInAs": "Sign in as",
    "login.signingIn": "Signing in…",
    "login.help": "Use the account provided by your campus administrator.",
    "auth.sessionExpired": "Your session has expired. Please sign in again.",
    "common.loading": "Loading…",
    "common.dismissMessage": "Dismiss message",
    "common.skipToContent": "Skip to content",
    "common.pageNotFound": "Page not found",
    "common.pageNotFoundDescription": "This page may have moved, or the address may be incorrect.",
    "common.returnDashboard": "Return to your dashboard",
    STAFF: "Office Staff",
    ADMIN: "Administrator",
  },
  my: {
    "staffAccountsPage.eyebrow": "တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု",
    "staffAccountsPage.title": "ဝန်ထမ်းအကောင့်များ",
    "staffAccountsPage.description": "စမတ်အဆောက်အအုံ စောင့်ကြည့်ရေးစနစ်အတွက် ရုံးဝန်ထမ်း အသုံးပြုခွင့်ကို စီမံပါ။",
    "staffAccountsPage.create": "ဝန်ထမ်းအကောင့် ဖန်တီးရန်",
    "staffAccountsPage.officeStaff": "ရုံးဝန်ထမ်းများ",
    "staffAccountsPage.oneAccount": "အကောင့်",
    "staffAccountsPage.accounts": "အကောင့်များ",
    "staffAccountsPage.loading": "ဖွင့်နေသည်…",
    "staffAccountsPage.retry": "ထပ်မံကြိုးစားရန်",
    "staffAccountsPage.refreshError": "နောက်ဆုံးအချက်အလက်များကို ပြန်လည်ဖွင့်၍ မရပါ။",
    "staffAccountsPage.facilitiesAccess": "တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု အသုံးပြုခွင့်",
    "staffAccountsPage.empty": "ရုံးဝန်ထမ်းအကောင့် မရှိသေးပါ။",
    "staffAccountsPage.accessNote": "အကောင့်အသစ်များသည် ရုံးဝန်ထမ်း အသုံးပြုခွင့်ကို ရရှိပါသည်။",
    "staffAccountsPage.nameRequired": "အမည် ထည့်ပါ။",
    "staffAccountsPage.passwordMismatch": "စကားဝှက်နှစ်ခု ကိုက်ညီရပါမည်။",
    "staffAccountsPage.createSuccess": "ဝန်ထမ်းအကောင့်ကို အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ။",
    "staffAccountsPage.createDialog": "ဝန်ထမ်းအကောင့် ဖန်တီးရန်",
    "staffAccountsPage.closeDialog": "ဝန်ထမ်းအကောင့် ဖောင်ကို ပိတ်ရန်",
    "staffAccountsPage.dialogIntro": "ရုံးဝန်ထမ်းတစ်ဦးအတွက် အသုံးပြုခွင့် ဖန်တီးပါ။",
    "staffAccountsPage.requiredValidation": "မဖြစ်မနေ ဖြည့်ရမည့် ဤအကွက်ကို ဖြည့်ပါ။",
    "staffAccountsPage.name": "အမည်",
    "staffAccountsPage.initialPassword": "အစပြု စကားဝှက်",
    "staffAccountsPage.passwordHint": "အနည်းဆုံး စာလုံး ၈ လုံး အသုံးပြုပါ။",
    "staffAccountsPage.confirmPassword": "စကားဝှက် အတည်ပြုရန်",
    "staffAccountsPage.saving": "သိမ်းဆည်းနေသည်…",
    "A user with this name already exists": "ဤအမည်ဖြင့် အသုံးပြုသူ ရှိပြီးဖြစ်သည်။",
    "Invalid login credentials or role": "ဝင်ရောက်ရန် အချက်အလက် သို့မဟုတ် အခန်းကဏ္ဍ မမှန်ပါ။",
    "shell.smartBuilding": "စမတ်အဆောက်အအုံ",
    "shell.monitoringSystem": "စောင့်ကြည့်ရေးစနစ်",
    "shell.smartCampusFacilities": "စမတ်တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု",
    "shell.campusManagement": "တက္ကသိုလ် စီမံခန့်ခွဲမှု",
    "shell.myWorkspace": "ကျွန်ုပ်၏ လုပ်ငန်းခွင်",
    "shell.mainNavigation": "အဓိက လမ်းညွှန်မှု",
    "shell.campusFoot": "စမတ်တက္ကသိုလ် · CET333",
    "shell.navigation": "လမ်းညွှန်မှု",
    "shell.closeMenu": "မီနူး ပိတ်ရန်",
    "shell.openMenu": "မီနူး ဖွင့်ရန်",
    "shell.smartCampus": "စမတ်တက္ကသိုလ်",
    "shell.campusFacilities": "တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု",
    "shell.footerTitle": "စမတ်အဆောက်အအုံ စောင့်ကြည့်ရေးစနစ်",
    "shell.footerTagline": "တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှုများကို ချိတ်ဆက်ထားသည်။",
    "login.sessionCheckUnavailable": "ဆက်ရှင် စစ်ဆေးမှုကို မရနိုင်ပါ",
    "login.sessionUnavailableTitle": "ယခုအချိန်တွင် သင်၏ ဆက်ရှင်ကို စစ်ဆေး၍ မရပါ။",
    "login.sessionUnavailableDescription": "သိမ်းဆည်းထားသော ဆက်ရှင်ကို ကာကွယ်ထားဆဲဖြစ်သည်။ ဝန်ဆောင်မှု ရနိုင်သည့်အခါ ထပ်မံကြိုးစားပါ။",
    "login.retrySession": "ဆက်ရှင် ပြန်လည်စစ်ဆေးရန်",
    "login.nameRequired": "အမည် ထည့်ပါ။",
    "login.monitoringSystem": "စောင့်ကြည့်ရေးစနစ်",
    "login.portalLabel": "စမတ်တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု ပေါ်တယ်",
    "login.monitoring": "စောင့်ကြည့်မှု။",
    "login.titleNote": "ပိုမိုချိတ်ဆက်ထားသော တက္ကသိုလ်။",
    "login.story": "တက္ကသိုလ်အဆောက်အအုံများကို စောင့်ကြည့်ပြီး ပြုပြင်ထိန်းသိမ်းရန် တင်ပြချက်များကို စီမံကာ ဝန်ဆောင်မှုများကို အဆင်ပြေစွာ လည်ပတ်စေပါ။",
    "login.campusMonitoring": "တက္ကသိုလ် စောင့်ကြည့်မှု",
    "login.maintenanceManagement": "ပြုပြင်ထိန်းသိမ်းမှု စီမံခန့်ခွဲမှု",
    "login.secureAccess": "လုံခြုံသော အခန်းကဏ္ဍအလိုက် အသုံးပြုခွင့်",
    "login.welcome": "သင်၏ လုပ်ငန်းခွင်မှ ကြိုဆိုပါသည်",
    "login.signIn": "ဝင်ရောက်ရန်",
    "login.accessPortal": "သင်၏ တက္ကသိုလ် အဆောက်အအုံဝန်ဆောင်မှု ပေါ်တယ်သို့ ဝင်ရောက်ပါ။",
    "login.requiredValidation": "မဖြစ်မနေ ဖြည့်ရမည့် ဤအကွက်ကို ဖြည့်ပါ။",
    "login.name": "အမည်",
    "login.namePlaceholder": "သင်၏ အမည် ထည့်ပါ",
    "login.password": "စကားဝှက်",
    "login.passwordPlaceholder": "သင်၏ စကားဝှက် ထည့်ပါ",
    "login.showPassword": "စကားဝှက် ပြရန်",
    "login.hidePassword": "စကားဝှက် ဖျောက်ရန်",
    "login.signInAs": "အဖြစ် ဝင်ရောက်ရန်",
    "login.signingIn": "ဝင်ရောက်နေသည်…",
    "login.help": "သင်၏ တက္ကသိုလ် စီမံခန့်ခွဲသူ ပေးထားသော အကောင့်ကို အသုံးပြုပါ။",
    "auth.sessionExpired": "သင်၏ ဆက်ရှင် သက်တမ်းကုန်သွားပါပြီ။ ထပ်မံဝင်ရောက်ပါ။",
    "common.loading": "ဖွင့်နေသည်…",
    "common.dismissMessage": "စာတိုကို ပိတ်ရန်",
    "common.skipToContent": "အဓိကအကြောင်းအရာသို့ ကျော်သွားရန်",
    "common.pageNotFound": "စာမျက်နှာကို မတွေ့ပါ",
    "common.pageNotFoundDescription": "ဤစာမျက်နှာကို ရွှေ့ထားနိုင်သည် သို့မဟုတ် လိပ်စာ မမှန်နိုင်ပါသည်။",
    "common.returnDashboard": "ပင်မစာမျက်နှာသို့ ပြန်သွားရန်",
    STAFF: "ရုံးဝန်ထမ်း",
    ADMIN: "စီမံခန့်ခွဲသူ",
  },
};
const accountManagementWords = {
  en: {
    "account.changePassword": "Change password",
    "account.closePasswordDialog": "Close change password dialog",
    "account.passwordIntro": "Choose a new password for your account.",
    "account.currentPassword": "Current password",
    "account.newPassword": "New password",
    "account.confirmNewPassword": "Confirm new password",
    "account.passwordHint": "Use at least 8 characters.",
    "account.requiredValidation": "Please complete this required field.",
    "account.passwordMismatch": "New passwords must match.",
    "account.passwordChanged": "Password changed successfully.",
    "account.changingPassword": "Changing password…",
    "Current password is incorrect": "Current password is incorrect.",
    "New passwords do not match": "New passwords must match.",
    "Account is disabled": "This account has been disabled.",
    ACTIVE: "Active",
    DISABLED: "Disabled",
    "staffAccountsPage.enable": "Enable",
    "staffAccountsPage.disable": "Disable",
    "staffAccountsPage.enabledSuccess": "Staff account enabled.",
    "staffAccountsPage.disabledSuccess": "Staff account disabled.",
  },
  my: {
    "account.changePassword": "စကားဝှက် ပြောင်းရန်",
    "account.closePasswordDialog": "စကားဝှက်ပြောင်းရန် ဖောင်ကို ပိတ်ရန်",
    "account.passwordIntro": "သင့်အကောင့်အတွက် စကားဝှက်အသစ် ရွေးချယ်ပါ။",
    "account.currentPassword": "လက်ရှိ စကားဝှက်",
    "account.newPassword": "စကားဝှက်အသစ်",
    "account.confirmNewPassword": "စကားဝှက်အသစ် အတည်ပြုရန်",
    "account.passwordHint": "အနည်းဆုံး စာလုံး ၈ လုံး အသုံးပြုပါ။",
    "account.requiredValidation": "မဖြစ်မနေ ဖြည့်ရမည့် ဤအကွက်ကို ဖြည့်ပါ။",
    "account.passwordMismatch": "စကားဝှက်အသစ်နှစ်ခု ကိုက်ညီရပါမည်။",
    "account.passwordChanged": "စကားဝှက်ကို အောင်မြင်စွာ ပြောင်းပြီးပါပြီ။",
    "account.changingPassword": "စကားဝှက် ပြောင်းနေသည်…",
    "Current password is incorrect": "လက်ရှိ စကားဝှက် မမှန်ပါ။",
    "New passwords do not match": "စကားဝှက်အသစ်နှစ်ခု ကိုက်ညီရပါမည်။",
    "Account is disabled": "ဤအကောင့်ကို ပိတ်ထားပါသည်။",
    ACTIVE: "အသုံးပြုနိုင်",
    DISABLED: "ပိတ်ထားသည်",
    "staffAccountsPage.enable": "အသုံးပြုခွင့်ပေးရန်",
    "staffAccountsPage.disable": "ပိတ်ရန်",
    "staffAccountsPage.enabledSuccess": "ဝန်ထမ်းအကောင့်ကို အသုံးပြုခွင့်ပေးပြီးပါပြီ။",
    "staffAccountsPage.disabledSuccess": "ဝန်ထမ်းအကောင့်ကို ပိတ်ပြီးပါပြီ။",
  },
};
const alertWords = {
  en: {
    "alertsPage.eyebrow": "CAMPUS OPERATIONS",
    "alertsPage.title": "Alerts",
    "alertsPage.description": "Review and manage manually created campus facility alerts.",
    "alertsPage.create": "Create alert",
    "alertsPage.summary": "Alert summary",
    "alertsPage.activeCount": "ACTIVE ALERTS",
    "alertsPage.activeCountNote": "Require current attention",
    "alertsPage.severity": "Severity",
    "alertsPage.category": "Category",
    "alertsPage.status": "Status",
    "alertsPage.allSeverities": "All severities",
    "alertsPage.allCategories": "All categories",
    "alertsPage.allStatuses": "All statuses",
    "alertsPage.clear": "Clear filters",
    "alertsPage.alertList": "Alert list",
    "alertsPage.oneAlert": "alert",
    "alertsPage.alerts": "alerts",
    "alertsPage.loading": "Loading alerts…",
    "alertsPage.retry": "Try again",
    "alertsPage.refreshError": "Could not refresh the latest alerts.",
    "alertsPage.empty": "No alerts found.",
    "alertsPage.emptyDescription": "Create an alert to begin monitoring campus issues.",
    "alertsPage.alert": "Alert",
    "alertsPage.location": "Location",
    "alertsPage.created": "Created",
    "alertsPage.action": "Action",
    "alertsPage.view": "View",
    "alertsPage.viewDetails": "View alert details",
    "alertsPage.generalBuilding": "General building alert",
    "alertsPage.createDialog": "Create alert",
    "alertsPage.closeDialog": "Close alert dialog",
    "alertsPage.building": "Building",
    "alertsPage.selectBuilding": "Select a building",
    "alertsPage.equipment": "Equipment",
    "alertsPage.equipmentHint": "Optional. Choose equipment after selecting a building.",
    "alertsPage.selectOption": "Select an option",
    "alertsPage.alertTitle": "Alert title",
    "alertsPage.descriptionLabel": "Description",
    "alertsPage.requiredFields": "Please complete all required alert fields.",
    "alertsPage.requiredValidation": "Please complete this required field.",
    "alertsPage.createAlert": "Create alert",
    "alertsPage.saving": "Saving…",
    "alertsPage.createSuccess": "Alert created successfully.",
    "alertsPage.alertDetails": "Alert details",
    "alertsPage.resolved": "Resolved",
    "alertsPage.resolve": "Resolve alert",
    "alertsPage.resolving": "Resolving…",
    "alertsPage.resolveSuccess": "Alert resolved successfully.",
    EQUIPMENT: "Equipment",
    ENERGY: "Energy",
    COMFORT: "Comfort",
    INFO: "Info",
    WARNING: "Warning",
    ACTIVE: "Active",
  },
  my: {
    "alertsPage.eyebrow": "တက္ကသိုလ် လုပ်ငန်းဆောင်ရွက်မှု",
    "alertsPage.title": "သတိပေးချက်များ",
    "alertsPage.description": "လက်ဖြင့်ဖန်တီးထားသော တက္ကသိုလ်အဆောက်အအုံ သတိပေးချက်များကို စစ်ဆေးစီမံပါ။",
    "alertsPage.create": "သတိပေးချက် ဖန်တီးရန်",
    "alertsPage.summary": "သတိပေးချက် အနှစ်ချုပ်",
    "alertsPage.activeCount": "လက်ရှိ သတိပေးချက်များ",
    "alertsPage.activeCountNote": "လက်ရှိ ဂရုပြုရန် လိုအပ်သည်",
    "alertsPage.severity": "ပြင်းထန်မှု",
    "alertsPage.category": "အမျိုးအစား",
    "alertsPage.status": "အခြေအနေ",
    "alertsPage.allSeverities": "ပြင်းထန်မှုအားလုံး",
    "alertsPage.allCategories": "အမျိုးအစားအားလုံး",
    "alertsPage.allStatuses": "အခြေအနေအားလုံး",
    "alertsPage.clear": "စစ်ထုတ်မှုများ ဖျက်ရန်",
    "alertsPage.alertList": "သတိပေးချက်စာရင်း",
    "alertsPage.oneAlert": "သတိပေးချက်",
    "alertsPage.alerts": "သတိပေးချက်များ",
    "alertsPage.loading": "သတိပေးချက်များ ဖွင့်နေသည်…",
    "alertsPage.retry": "ထပ်မံကြိုးစားရန်",
    "alertsPage.refreshError": "နောက်ဆုံး သတိပေးချက်များကို ပြန်လည်ဖွင့်၍ မရပါ။",
    "alertsPage.empty": "သတိပေးချက် မတွေ့ပါ။",
    "alertsPage.emptyDescription": "တက္ကသိုလ်ပြဿနာများကို စောင့်ကြည့်ရန် သတိပေးချက်တစ်ခု ဖန်တီးပါ။",
    "alertsPage.alert": "သတိပေးချက်",
    "alertsPage.location": "တည်နေရာ",
    "alertsPage.created": "ဖန်တီးသည့်အချိန်",
    "alertsPage.action": "လုပ်ဆောင်ချက်",
    "alertsPage.view": "ကြည့်ရန်",
    "alertsPage.viewDetails": "သတိပေးချက် အသေးစိတ်ကြည့်ရန်",
    "alertsPage.generalBuilding": "အထွေထွေ အဆောက်အအုံ သတိပေးချက်",
    "alertsPage.createDialog": "သတိပေးချက် ဖန်တီးရန်",
    "alertsPage.closeDialog": "သတိပေးချက်ဖောင်ကို ပိတ်ရန်",
    "alertsPage.building": "အဆောက်အအုံ",
    "alertsPage.selectBuilding": "အဆောက်အအုံ ရွေးချယ်ပါ",
    "alertsPage.equipment": "ပစ္စည်းကိရိယာ",
    "alertsPage.equipmentHint": "ရွေးချယ်နိုင်သည်။ အဆောက်အအုံရွေးချယ်ပြီးနောက် ပစ္စည်းကိရိယာ ရွေးပါ။",
    "alertsPage.selectOption": "ရွေးချယ်ပါ",
    "alertsPage.alertTitle": "သတိပေးချက် ခေါင်းစဉ်",
    "alertsPage.descriptionLabel": "ဖော်ပြချက်",
    "alertsPage.requiredFields": "လိုအပ်သော သတိပေးချက်အကွက်များကို ဖြည့်ပါ။",
    "alertsPage.requiredValidation": "မဖြစ်မနေ ဖြည့်ရမည့် ဤအကွက်ကို ဖြည့်ပါ။",
    "alertsPage.createAlert": "သတိပေးချက် ဖန်တီးရန်",
    "alertsPage.saving": "သိမ်းဆည်းနေသည်…",
    "alertsPage.createSuccess": "သတိပေးချက်ကို အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ။",
    "alertsPage.alertDetails": "သတိပေးချက် အသေးစိတ်",
    "alertsPage.resolved": "ဖြေရှင်းပြီး",
    "alertsPage.resolve": "သတိပေးချက် ဖြေရှင်းရန်",
    "alertsPage.resolving": "ဖြေရှင်းနေသည်…",
    "alertsPage.resolveSuccess": "သတိပေးချက်ကို အောင်မြင်စွာ ဖြေရှင်းပြီးပါပြီ။",
    EQUIPMENT: "ပစ္စည်းကိရိယာ",
    ENERGY: "စွမ်းအင်",
    COMFORT: "သက်တောင့်သက်သာ",
    INFO: "အချက်အလက်",
    WARNING: "သတိပေး",
    ACTIVE: "လက်ရှိ",
  },
};
const energyWords = {
  en: {
    "energyPage.eyebrow": "CAMPUS ENERGY",
    "energyPage.title": "Energy Intelligence",
    "energyPage.description": "Compare recent building energy use with a clear, explainable baseline.",
    "energyPage.refresh": "Refresh",
    "energyPage.refreshError": "Could not refresh the latest energy data.",
    "energyPage.summary": "Campus energy summary",
    "energyPage.highUsage": "HIGH USAGE",
    "energyPage.highUsageNote": "Buildings above the recent baseline",
    "energyPage.rule": "HIGH-USAGE RULE",
    "energyPage.ruleNote": "Above the recent average",
    "energyPage.explanation": "A building is marked High Usage when its latest reading is 20% or more above the average of its previous five readings.",
    "energyPage.loading": "Loading energy intelligence…",
    "energyPage.retry": "Try again",
    "energyPage.empty": "No buildings are available.",
    "energyPage.noData": "No energy readings available.",
    "energyPage.noTrend": "No trend data available.",
    "energyPage.noSelection": "Select a building",
    "energyPage.latest": "Latest consumption",
    "energyPage.recentAverage": "Recent average",
    "energyPage.reading": "Reading",
    "energyPage.highReasonStart": "Latest use is",
    "energyPage.highReasonEnd": "above the average; threshold is",
    "energyPage.comparison": "Building comparison",
    "energyPage.recentTrend": "Recent trend",
    "energyPage.consumption": "Consumption",
    NORMAL: "Normal",
    HIGH_USAGE: "High Usage",
    UP: "Up",
    DOWN: "Down",
    STABLE: "Stable",
    NO_DATA: "No data",
  },
  my: {
    "energyPage.eyebrow": "တက္ကသိုလ် စွမ်းအင်",
    "energyPage.title": "စွမ်းအင် အချက်အလက်",
    "energyPage.description": "ရှင်းလင်းနားလည်နိုင်သော အခြေခံနှင့် အဆောက်အအုံများ၏ လတ်တလောစွမ်းအင်သုံးစွဲမှုကို နှိုင်းယှဉ်ပါ။",
    "energyPage.refresh": "ပြန်လည်ဖွင့်ရန်",
    "energyPage.refreshError": "နောက်ဆုံး စွမ်းအင်အချက်အလက်များကို ပြန်လည်ဖွင့်၍ မရပါ။",
    "energyPage.summary": "တက္ကသိုလ် စွမ်းအင် အနှစ်ချုပ်",
    "energyPage.highUsage": "သုံးစွဲမှုမြင့်",
    "energyPage.highUsageNote": "လတ်တလော အခြေခံထက် မြင့်သော အဆောက်အအုံများ",
    "energyPage.rule": "သုံးစွဲမှုမြင့် စည်းမျဉ်း",
    "energyPage.ruleNote": "လတ်တလော ပျမ်းမျှထက် မြင့်သည်",
    "energyPage.explanation": "နောက်ဆုံးဖတ်ရှုမှုသည် ယခင်ဖတ်ရှုမှု ၅ ခု၏ ပျမ်းမျှထက် ၂၀% သို့မဟုတ် ထို့ထက်ပိုမြင့်လျှင် သုံးစွဲမှုမြင့်အဖြစ် သတ်မှတ်သည်။",
    "energyPage.loading": "စွမ်းအင်အချက်အလက် ဖွင့်နေသည်…",
    "energyPage.retry": "ထပ်မံကြိုးစားရန်",
    "energyPage.empty": "အဆောက်အအုံ မရှိပါ။",
    "energyPage.noData": "စွမ်းအင်ဖတ်ရှုမှု မရှိပါ။",
    "energyPage.noTrend": "လမ်းကြောင်းအချက်အလက် မရှိပါ။",
    "energyPage.noSelection": "အဆောက်အအုံ ရွေးချယ်ပါ",
    "energyPage.latest": "နောက်ဆုံး သုံးစွဲမှု",
    "energyPage.recentAverage": "လတ်တလော ပျမ်းမျှ",
    "energyPage.reading": "ဖတ်ရှုမှု",
    "energyPage.highReasonStart": "နောက်ဆုံးသုံးစွဲမှုသည်",
    "energyPage.highReasonEnd": "ပျမ်းမျှထက်ပိုမြင့်သည်။ သတ်မှတ်ချက်မှာ",
    "energyPage.comparison": "အဆောက်အအုံ နှိုင်းယှဉ်မှု",
    "energyPage.recentTrend": "လတ်တလော လမ်းကြောင်း",
    "energyPage.consumption": "သုံးစွဲမှု",
    NORMAL: "ပုံမှန်",
    HIGH_USAGE: "သုံးစွဲမှုမြင့်",
    UP: "မြင့်တက်",
    DOWN: "လျော့ကျ",
    STABLE: "တည်ငြိမ်",
    NO_DATA: "အချက်အလက်မရှိ",
  },
};
const comfortWords = {
  en: {
    "comfortPage.eyebrow": "CAMPUS COMFORT",
    "comfortPage.title": "Comfort Intelligence",
    "comfortPage.description": "Review building temperature and humidity against simple, explainable comfort ranges.",
    "comfortPage.refresh": "Refresh",
    "comfortPage.refreshError": "Could not refresh the latest comfort data.",
    "comfortPage.summary": "Campus comfort summary",
    "comfortPage.uncomfortable": "UNCOMFORTABLE",
    "comfortPage.uncomfortableNote": "Buildings outside acceptable ranges",
    "comfortPage.attention": "ATTENTION",
    "comfortPage.attentionNote": "Buildings outside preferred ranges",
    "comfortPage.explanation": "Comfortable: 20–26°C and 40–60% humidity. Attention: 18–28°C or 30–70% humidity. Outside those acceptable ranges is Uncomfortable.",
    "comfortPage.loading": "Loading comfort intelligence…",
    "comfortPage.retry": "Try again",
    "comfortPage.empty": "No buildings are available.",
    "comfortPage.noData": "No temperature or humidity readings available.",
    "comfortPage.noTrend": "No comfort trend data available.",
    "comfortPage.noSelection": "Select a building",
    "comfortPage.reason": "Reason",
    "comfortPage.recommendation": "Recommendation",
    "comfortPage.reading": "Reading",
    "comfortPage.recentTrend": "Temperature & humidity trend",
    "comfortPage.temperature": "Temperature (°C)",
    "comfortPage.humidity": "Humidity (%)",
    COMFORTABLE: "Comfortable",
    UNCOMFORTABLE: "Uncomfortable",
    WITHIN_PREFERRED_RANGES: "Temperature and humidity are within preferred ranges.",
    TEMPERATURE_OUTSIDE_PREFERRED_RANGE: "Temperature is outside the preferred range.",
    HUMIDITY_OUTSIDE_PREFERRED_RANGE: "Humidity is outside the preferred range.",
    TEMPERATURE_AND_HUMIDITY_NEED_ADJUSTMENT: "Temperature and humidity both need adjustment.",
    TEMPERATURE_OUTSIDE_ACCEPTABLE_RANGE: "Temperature is outside the acceptable range.",
    HUMIDITY_OUTSIDE_ACCEPTABLE_RANGE: "Humidity is outside the acceptable range.",
    TEMPERATURE_AND_HUMIDITY_OUTSIDE_ACCEPTABLE_RANGE: "Temperature and humidity are outside acceptable ranges.",
    NO_ACTION_NEEDED: "No action needed.",
    ADJUST_TEMPERATURE: "Adjust the building temperature.",
    ADJUST_HUMIDITY: "Adjust the building humidity.",
    ADJUST_TEMPERATURE_AND_HUMIDITY: "Adjust temperature and humidity.",
  },
  my: {
    "comfortPage.eyebrow": "တက္ကသိုလ် သက်တောင့်သက်သာ",
    "comfortPage.title": "သက်တောင့်သက်သာ အချက်အလက်",
    "comfortPage.description": "ရှင်းလင်းနားလည်နိုင်သော သက်တောင့်သက်သာအတိုင်းအတာများနှင့် အဆောက်အအုံ အပူချိန်၊ စိုထိုင်းဆကို စစ်ဆေးပါ။",
    "comfortPage.refresh": "ပြန်လည်ဖွင့်ရန်",
    "comfortPage.refreshError": "နောက်ဆုံး သက်တောင့်သက်သာအချက်အလက်များကို ပြန်လည်ဖွင့်၍ မရပါ။",
    "comfortPage.summary": "တက္ကသိုလ် သက်တောင့်သက်သာ အနှစ်ချုပ်",
    "comfortPage.uncomfortable": "မသက်တောင့်မသက်သာ",
    "comfortPage.uncomfortableNote": "လက်ခံနိုင်သောအတိုင်းအတာ ပြင်ပရှိ အဆောက်အအုံများ",
    "comfortPage.attention": "စစ်ဆေးရန်လို",
    "comfortPage.attentionNote": "လိုလားသောအတိုင်းအတာ ပြင်ပရှိ အဆောက်အအုံများ",
    "comfortPage.explanation": "သက်တောင့်သက်သာရှိမှုမှာ ၂၀–၂၆°C နှင့် စိုထိုင်းဆ ၄၀–၆၀% ဖြစ်သည်။ စစ်ဆေးရန်မှာ ၁၈–၂၈°C သို့မဟုတ် ၃၀–၇၀% ဖြစ်သည်။ လက်ခံနိုင်သောအတိုင်းအတာ ပြင်ပသည် မသက်တောင့်မသက်သာဖြစ်သည်။",
    "comfortPage.loading": "သက်တောင့်သက်သာအချက်အလက် ဖွင့်နေသည်…",
    "comfortPage.retry": "ထပ်မံကြိုးစားရန်",
    "comfortPage.empty": "အဆောက်အအုံ မရှိပါ။",
    "comfortPage.noData": "အပူချိန် သို့မဟုတ် စိုထိုင်းဆဖတ်ရှုမှု မရှိပါ။",
    "comfortPage.noTrend": "သက်တောင့်သက်သာ လမ်းကြောင်းအချက်အလက် မရှိပါ။",
    "comfortPage.noSelection": "အဆောက်အအုံ ရွေးချယ်ပါ",
    "comfortPage.reason": "အကြောင်းရင်း",
    "comfortPage.recommendation": "အကြံပြုချက်",
    "comfortPage.reading": "ဖတ်ရှုမှု",
    "comfortPage.recentTrend": "အပူချိန်နှင့် စိုထိုင်းဆ လမ်းကြောင်း",
    "comfortPage.temperature": "အပူချိန် (°C)",
    "comfortPage.humidity": "စိုထိုင်းဆ (%)",
    COMFORTABLE: "သက်တောင့်သက်သာ",
    UNCOMFORTABLE: "မသက်တောင့်မသက်သာ",
    WITHIN_PREFERRED_RANGES: "အပူချိန်နှင့် စိုထိုင်းဆသည် လိုလားသောအတိုင်းအတာအတွင်း ရှိပါသည်။",
    TEMPERATURE_OUTSIDE_PREFERRED_RANGE: "အပူချိန်သည် လိုလားသောအတိုင်းအတာ ပြင်ပတွင် ရှိပါသည်။",
    HUMIDITY_OUTSIDE_PREFERRED_RANGE: "စိုထိုင်းဆသည် လိုလားသောအတိုင်းအတာ ပြင်ပတွင် ရှိပါသည်။",
    TEMPERATURE_AND_HUMIDITY_NEED_ADJUSTMENT: "အပူချိန်နှင့် စိုထိုင်းဆ နှစ်ခုလုံး ချိန်ညှိရန်လိုပါသည်။",
    TEMPERATURE_OUTSIDE_ACCEPTABLE_RANGE: "အပူချိန်သည် လက်ခံနိုင်သောအတိုင်းအတာ ပြင်ပတွင် ရှိပါသည်။",
    HUMIDITY_OUTSIDE_ACCEPTABLE_RANGE: "စိုထိုင်းဆသည် လက်ခံနိုင်သောအတိုင်းအတာ ပြင်ပတွင် ရှိပါသည်။",
    TEMPERATURE_AND_HUMIDITY_OUTSIDE_ACCEPTABLE_RANGE: "အပူချိန်နှင့် စိုထိုင်းဆသည် လက်ခံနိုင်သောအတိုင်းအတာ ပြင်ပတွင် ရှိပါသည်။",
    NO_ACTION_NEEDED: "လုပ်ဆောင်ရန် မလိုပါ။",
    ADJUST_TEMPERATURE: "အဆောက်အအုံအပူချိန်ကို ချိန်ညှိပါ။",
    ADJUST_HUMIDITY: "အဆောက်အအုံစိုထိုင်းဆကို ချိန်ညှိပါ။",
    ADJUST_TEMPERATURE_AND_HUMIDITY: "အပူချိန်နှင့် စိုထိုင်းဆကို ချိန်ညှိပါ။",
  },
};
const campusOperationsWords = {
  en: {
    "campusPage.eyebrow": "CAMPUS OPERATIONS",
    "campusPage.title": "Campus Operations",
    "campusPage.description": "A concise operational view across the three campus buildings.",
    "campusPage.refresh": "Refresh",
    "campusPage.refreshError": "Could not refresh the campus overview.",
    "campusPage.loading": "Loading campus operations…",
    "campusPage.retry": "Try again",
    "campusPage.empty": "No campus building data is available.",
    "campusPage.summary": "Campus operations summary",
    "campusPage.openRequests": "OPEN REQUESTS",
    "campusPage.openRequestsNote": "Pending and in progress",
    "campusPage.equipmentAttention": "EQUIPMENT ATTENTION",
    "campusPage.equipmentAttentionNote": "Maintenance required or out of service",
    "campusPage.activeAlerts": "ACTIVE ALERTS",
    "campusPage.highUsage": "HIGH USAGE",
    "campusPage.critical": "critical",
    "campusPage.uncomfortable": "uncomfortable",
    "campusPage.buildingOverview": "Building overview",
    "campusPage.highPriority": "high priority",
    "campusPage.energy": "Energy",
    "campusPage.comfort": "Comfort",
    "campusPage.noData": "No data",
    "campusPage.links": "Operations links",
    "campusPage.requests": "Requests",
    "campusPage.alerts": "Alerts",
    "campusPage.monitoring": "Monitoring",
  },
  my: {
    "campusPage.eyebrow": "တက္ကသိုလ် လုပ်ငန်းဆောင်ရွက်မှု",
    "campusPage.title": "တက္ကသိုလ် လုပ်ငန်းဆောင်ရွက်မှု",
    "campusPage.description": "တက္ကသိုလ်အဆောက်အအုံ သုံးခုအတွက် ရှင်းလင်းသည့် လုပ်ငန်းအခြေအနေ မြင်ကွင်း။",
    "campusPage.refresh": "ပြန်လည်ဖွင့်ရန်",
    "campusPage.refreshError": "တက္ကသိုလ်အနှစ်ချုပ်ကို ပြန်လည်ဖွင့်၍ မရပါ။",
    "campusPage.loading": "တက္ကသိုလ်လုပ်ငန်းဆောင်ရွက်မှု ဖွင့်နေသည်…",
    "campusPage.retry": "ထပ်မံကြိုးစားရန်",
    "campusPage.empty": "တက္ကသိုလ်အဆောက်အအုံအချက်အလက် မရှိပါ။",
    "campusPage.summary": "တက္ကသိုလ်လုပ်ငန်းဆောင်ရွက်မှု အနှစ်ချုပ်",
    "campusPage.openRequests": "ဖွင့်လှစ်ထားသော တင်ပြချက်များ",
    "campusPage.openRequestsNote": "စောင့်ဆိုင်းနေပြီး ဆောင်ရွက်နေသည်",
    "campusPage.equipmentAttention": "ပစ္စည်းကိရိယာ စစ်ဆေးရန်လို",
    "campusPage.equipmentAttentionNote": "ပြုပြင်ရန်လို သို့မဟုတ် အသုံးမပြုနိုင်",
    "campusPage.activeAlerts": "လက်ရှိ သတိပေးချက်များ",
    "campusPage.highUsage": "သုံးစွဲမှုမြင့်",
    "campusPage.critical": "အရေးပေါ်",
    "campusPage.uncomfortable": "မသက်တောင့်မသက်သာ",
    "campusPage.buildingOverview": "အဆောက်အအုံ အနှစ်ချုပ်",
    "campusPage.highPriority": "ဦးစားပေးမြင့်",
    "campusPage.energy": "စွမ်းအင်",
    "campusPage.comfort": "သက်တောင့်သက်သာ",
    "campusPage.noData": "အချက်အလက်မရှိ",
    "campusPage.links": "လုပ်ငန်းဆောင်ရွက်မှု လင့်ခ်များ",
    "campusPage.requests": "တင်ပြချက်များ",
    "campusPage.alerts": "သတိပေးချက်များ",
    "campusPage.monitoring": "စောင့်ကြည့်မှု",
  },
};
const words = {
  en: { ...staffDashboardWords.en, ...newRequestWords.en, ...myRequestsWords.en, ...requestDetailWords.en, ...adminRequestWords.en, ...equipmentMaintenanceWords.en, ...monitoringWords.en, ...finalLocalizationWords.en, ...accountManagementWords.en, ...alertWords.en, ...energyWords.en, ...comfortWords.en, ...campusOperationsWords.en, dashboard:"Dashboard", newRequest:"New Request", myRequests:"My Requests", requests:"Requests", monitoring:"Building Monitoring", equipment:"Equipment", maintenance:"Maintenance History", staffAccounts:"Staff Accounts", alerts:"Alerts", energy:"Energy Intelligence", comfort:"Comfort Intelligence", campusOperations:"Campus Operations", signOut:"Sign out", light:"Light", dark:"Dark", system:"System", theme:"Colour theme", language:"Language", PENDING:"Pending", IN_PROGRESS:"In Progress", RESOLVED:"Resolved", LOW:"Low", MEDIUM:"Medium", HIGH:"High", OPERATIONAL:"Operational", MAINTENANCE_REQUIRED:"Maintenance Required", OUT_OF_SERVICE:"Out of Service", NORMAL:"Normal", ATTENTION:"Attention", CRITICAL:"Critical", "Equipment management":"Equipment management", "Maintenance history":"Maintenance history", "Staff accounts":"Staff accounts", "Building monitoring":"Building monitoring", "Request management":"Request management", "Facilities overview":"Facilities overview" },
  my: { ...staffDashboardWords.my, ...newRequestWords.my, ...myRequestsWords.my, ...requestDetailWords.my, ...adminRequestWords.my, ...equipmentMaintenanceWords.my, ...monitoringWords.my, ...finalLocalizationWords.my, ...accountManagementWords.my, ...alertWords.my, ...energyWords.my, ...comfortWords.my, ...campusOperationsWords.my, dashboard:"ပင်မစာမျက်နှာ", newRequest:"ပြုပြင်ရန် တင်ပြရန်", myRequests:"ကျွန်ုပ်၏ တင်ပြချက်များ", requests:"တင်ပြချက်များ", monitoring:"အဆောက်အအုံ စောင့်ကြည့်မှု", equipment:"ပစ္စည်းကိရိယာများ", maintenance:"ပြုပြင်ထိန်းသိမ်းမှု မှတ်တမ်း", staffAccounts:"ဝန်ထမ်းအကောင့်များ", alerts:"သတိပေးချက်များ", energy:"စွမ်းအင် အချက်အလက်", comfort:"သက်တောင့်သက်သာ အချက်အလက်", campusOperations:"တက္ကသိုလ် လုပ်ငန်းဆောင်ရွက်မှု", signOut:"ထွက်မည်", light:"အလင်း", dark:"အမှောင်", system:"စနစ်", theme:"အရောင်အဆင်း", language:"ဘာသာစကား", PENDING:"စောင့်ဆိုင်းနေ", IN_PROGRESS:"ဆောင်ရွက်နေ", RESOLVED:"ပြီးစီး", LOW:"နိမ့်", MEDIUM:"အလယ်", HIGH:"မြင့်", OPERATIONAL:"အသုံးပြုနိုင်", MAINTENANCE_REQUIRED:"ပြုပြင်ရန်လို", OUT_OF_SERVICE:"အသုံးမပြုနိုင်", NORMAL:"ပုံမှန်", ATTENTION:"စစ်ဆေးရန်လို", CRITICAL:"အရေးပေါ်", "Equipment management":"ပစ္စည်းကိရိယာ စီမံခန့်ခွဲမှု", "Maintenance history":"ပြုပြင်ထိန်းသိမ်းမှု မှတ်တမ်း", "Staff accounts":"ဝန်ထမ်းအကောင့်များ", "Building monitoring":"အဆောက်အအုံ စောင့်ကြည့်မှု", "Request management":"တင်ပြချက် စီမံခန့်ခွဲမှု", "Facilities overview":"အဆောက်အအုံ အနှစ်ချုပ်" },
};
export const useLanguage = () => useContext(Context);
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem(key) === "my" ? "my" : "en");
  useEffect(() => { localStorage.setItem(key, language); document.documentElement.lang = language; }, [language]);
  const t = (value) => words[language][value] || words.en[value] || value;
  return <Context.Provider value={{ language, setLanguage, t }}>{children}</Context.Provider>;
}
