"""initial database schema

Revision ID: 9cf1817549e9
Revises: 
Create Date: 2026-09-06 22:49:19.154877
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9cf1817549e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('building_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('building_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('building_id'),
    sa.UniqueConstraint('building_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('STAFF', 'ADMIN')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('environmental_readings',
    sa.Column('reading_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('energy_consumption', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('energy_consumption >= 0', name='ck_environmental_readings_energy'),
    sa.CheckConstraint('humidity >= 0 AND humidity <= 100', name='ck_environmental_readings_humidity'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_index('ix_environmental_readings_building_id_recorded_at', 'environmental_readings', ['building_id', 'recorded_at'], unique=False)
    op.create_table('equipment',
    sa.Column('equipment_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('equipment_name', sa.String(length=150), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPERATIONAL', 'MAINTENANCE_REQUIRED', 'OUT_OF_SERVICE')", name='ck_equipment_status'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_index(op.f('ix_equipment_building_id'), 'equipment', ['building_id'], unique=False)
    op.create_index(op.f('ix_equipment_status'), 'equipment', ['status'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('request_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('room_location', sa.String(length=150), nullable=False),
    sa.Column('fault_category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('LOW', 'MEDIUM', 'HIGH')", name='ck_maintenance_requests_priority'),
    sa.CheckConstraint("status IN ('PENDING', 'IN_PROGRESS', 'RESOLVED')", name='ck_maintenance_requests_status'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_maintenance_requests_assigned_to'), 'maintenance_requests', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_building_id'), 'maintenance_requests', ['building_id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_created_at'), 'maintenance_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_equipment_id'), 'maintenance_requests', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_priority'), 'maintenance_requests', ['priority'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_status'), 'maintenance_requests', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_submitted_by'), 'maintenance_requests', ['submitted_by'], unique=False)
    op.create_table('maintenance_history',
    sa.Column('history_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=False),
    sa.Column('action_details', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['completed_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.request_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_maintenance_history_completed_at'), 'maintenance_history', ['completed_at'], unique=False)
    op.create_index(op.f('ix_maintenance_history_completed_by'), 'maintenance_history', ['completed_by'], unique=False)
    op.create_index(op.f('ix_maintenance_history_equipment_id'), 'maintenance_history', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_history_request_id'), 'maintenance_history', ['request_id'], unique=False)
    op.create_table('request_status_history',
    sa.Column('status_history_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("new_status IN ('PENDING', 'IN_PROGRESS', 'RESOLVED')", name='ck_request_status_history_new_status'),
    sa.CheckConstraint("previous_status IS NULL OR previous_status IN ('PENDING', 'IN_PROGRESS', 'RESOLVED')", name='ck_request_status_history_previous_status'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('status_history_id')
    )
    op.create_index(op.f('ix_request_status_history_changed_at'), 'request_status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_request_status_history_changed_by'), 'request_status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_request_status_history_request_id'), 'request_status_history', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_status_history_request_id'), table_name='request_status_history')
    op.drop_index(op.f('ix_request_status_history_changed_by'), table_name='request_status_history')
    op.drop_index(op.f('ix_request_status_history_changed_at'), table_name='request_status_history')
    op.drop_table('request_status_history')
    op.drop_index(op.f('ix_maintenance_history_request_id'), table_name='maintenance_history')
    op.drop_index(op.f('ix_maintenance_history_equipment_id'), table_name='maintenance_history')
    op.drop_index(op.f('ix_maintenance_history_completed_by'), table_name='maintenance_history')
    op.drop_index(op.f('ix_maintenance_history_completed_at'), table_name='maintenance_history')
    op.drop_table('maintenance_history')
    op.drop_index(op.f('ix_maintenance_requests_submitted_by'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_status'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_priority'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_equipment_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_created_at'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_building_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_assigned_to'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_equipment_status'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_building_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index('ix_environmental_readings_building_id_recorded_at', table_name='environmental_readings')
    op.drop_table('environmental_readings')
    op.drop_table('users')
    op.drop_table('buildings')
    # ### end Alembic commands ###
