import { useEffect, useState } from "react";
import { CirclePlus, Pencil, Trash2 } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import { useResource } from "../hooks/useResource";
import { useAction } from "../hooks/useAction";
import { useLanguage } from "../context/LanguageContext";
import { useToast } from "../context/ToastContext";
import { equipmentService } from "../services/equipmentService";
import { buildingService } from "../services/buildingService";
import { roomService } from "../services/roomService";
import { EquipmentIntelligencePanel } from "./EquipmentIntelligence";
import { EquipmentSensorsPanel } from "./EquipmentSensors";
import { Badge, EmptyState, ErrorAlert, Field, Modal, PageHeader, ResourceState, SubmitButton } from "../components/UI";
import { equipmentStatuses } from "../utils/format";

const types = ["Air Conditioning", "Lighting", "Projector", "Computer / IT", "AV Equipment", "Lift", "Water Pump", "Fire / Safety Device", "Other"];
export default function Equipment() {
  const { t } = useLanguage(); const [params, setParams] = useSearchParams();
  const tab = ["intelligence", "sensors"].includes(params.get("tab")) ? params.get("tab") : "management";
  return <><PageHeader eyebrow={t("equipmentPage.eyebrow")} title={t("equipmentPage.title")} description={t("equipmentPage.description")} />
    <div className="tabs" role="tablist" aria-label={t("equipmentPage.tabs")}><button role="tab" aria-selected={tab === "management"} className={tab === "management" ? "active" : ""} onClick={() => setParams({})}>{t("equipmentPage.managementTab")}</button><button role="tab" aria-selected={tab === "intelligence"} className={tab === "intelligence" ? "active" : ""} onClick={() => setParams({ tab: "intelligence" })}>{t("equipmentPage.intelligenceTab")}</button><button role="tab" aria-selected={tab === "sensors"} className={tab === "sensors" ? "active" : ""} onClick={() => setParams({ tab: "sensors" })}>{t("equipmentPage.sensorsTab")}</button></div>
    {tab === "management" ? <Management /> : tab === "intelligence" ? <EquipmentIntelligencePanel /> : <EquipmentSensorsPanel />}</>;
}
function Management() {
  const { t } = useLanguage(); const toast = useToast(); const [building, setBuilding] = useState(""), [status, setStatus] = useState(""), [search, setSearch] = useState(""), [editing, setEditing] = useState(null), [removing, setRemoving] = useState(null);
  const resource = useResource(() => equipmentService.list(building ? { building_id: building } : undefined), building); const buildings = useResource(buildingService.list);
  const items = (resource.data || []).filter((item) => (!status || item.status === status) && [item.equipment_name,item.equipment_type,item.building.building_name,item.room?.room_name].filter(Boolean).join(" ").toLowerCase().includes(search.toLowerCase()));
  return <><section className="panel filter-panel"><div className="filters"><Field label={t("equipmentPage.search")}>{id=><input id={id} value={search} onChange={e=>setSearch(e.target.value)} placeholder={t("equipmentPage.searchPlaceholder")}/>}</Field><Field label={t("equipmentPage.building")}>{id=><select id={id} value={building} onChange={e=>setBuilding(e.target.value)}><option value="">{t("equipmentPage.allBuildings")}</option>{buildings.data?.map(b=><option key={b.building_id} value={b.building_id}>{b.building_name}</option>)}</select>}</Field><Field label={t("equipmentPage.status")}>{id=><select id={id} value={status} onChange={e=>setStatus(e.target.value)}><option value="">{t("equipmentPage.allStatuses")}</option>{equipmentStatuses.map(v=><option key={v} value={v}>{t(v)}</option>)}</select>}</Field><button className="text-button" onClick={()=>{setBuilding("");setStatus("");setSearch("")}}>{t("equipmentPage.clear")}</button></div></section>
  <section className="panel"><div className="panel-heading"><h2>{t("equipmentPage.campusEquipment")}</h2><button className="button" onClick={()=>setEditing({})}><CirclePlus size={18}/>{t("equipmentPage.add")}</button></div><ResourceState resource={resource} copy={{loading:t("equipmentPage.loading"),retry:t("equipmentPage.retry"),error:t}}>{items.length ? <div className="mobile-records management-table">{items.map(item=><article className="record-card" key={item.equipment_id}><div className="record-top"><strong>{item.equipment_name}</strong><Badge value={item.status}/></div><p>{item.equipment_type} · {item.building.building_name} · {item.room ? `${item.room.room_number} · ${item.room.room_name}` : t("equipmentPage.buildingLevel")}</p><div className="form-actions"><button className="text-button" onClick={()=>setEditing(item)}><Pencil size={15}/>{t("equipmentPage.edit")}</button><button className="text-button critical-action" onClick={()=>setRemoving(item)}><Trash2 size={15}/>{t("equipmentPage.remove")}</button></div></article>)}</div> : <EmptyState title={t("equipmentPage.empty")}/>}</ResourceState></section>
  {editing && <EquipmentForm equipment={editing} buildings={buildings.data||[]} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);resource.refresh({background:true})}}/>}{removing && <RemoveDialog equipment={removing} onClose={()=>setRemoving(null)} onRemoved={()=>{setRemoving(null);resource.refresh({background:true});toast(t("equipmentPage.removeSuccess"))}}/>}</>;
}
function EquipmentForm({equipment,buildings,onClose,onSaved}) { const {t}=useLanguage(); const action=useAction(),toast=useToast(), edit=Boolean(equipment.equipment_id); const [buildingId,setBuildingId]=useState(edit?String(equipment.building.building_id):"");const [roomId,setRoomId]=useState(equipment.room?String(equipment.room.room_id):"");const rooms=useResource(()=>roomService.list(buildingId?{building_id:buildingId}:undefined),buildingId);useEffect(()=>{if(roomId&&!rooms.loading&&rooms.data&&!rooms.data.some(r=>String(r.room_id)===roomId))setRoomId("")},[buildingId,rooms.data,rooms.loading,roomId]);function submit(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));body.room_id=roomId?Number(roomId):null;if(!edit)body.building_id=Number(buildingId);action.run(async()=>{edit?await equipmentService.update(equipment.equipment_id,body):await equipmentService.create(body);toast(t(edit?"equipmentPage.updateSuccess":"equipmentPage.addSuccess"));onSaved()})}return <Modal title={t(edit?"equipmentPage.editDialog":"equipmentPage.addDialog")} onClose={onClose}><ErrorAlert message={t(action.error)}/><form onSubmit={submit}><Field label={t("equipmentPage.name")} required>{id=><input id={id} name="equipment_name" required defaultValue={equipment.equipment_name||""}/>}</Field>{edit?<div className="readonly-field"><span>{t("equipmentPage.building")}</span><strong>{equipment.building.building_name}</strong></div>:<Field label={t("equipmentPage.building")} required>{id=><select id={id} required value={buildingId} onChange={e=>{setBuildingId(e.target.value);setRoomId("")}}><option value="">{t("equipmentPage.selectBuilding")}</option>{buildings.map(b=><option key={b.building_id} value={b.building_id}>{b.building_name}</option>)}</select>}</Field>}<Field label={t("equipmentPage.equipmentType")} required>{id=><select id={id} name="equipment_type" required defaultValue={equipment.equipment_type||""}><option value="">{t("equipmentPage.selectType")}</option>{types.map(v=><option key={v} value={v}>{t(v)}</option>)}</select>}</Field><Field label={t("equipmentPage.room")} hint={t("equipmentPage.roomHint")}>{id=><select id={id} value={roomId} onChange={e=>setRoomId(e.target.value)} disabled={!buildingId||rooms.loading}><option value="">{t("equipmentPage.buildingLevel")}</option>{rooms.data?.map(r=><option key={r.room_id} value={r.room_id}>{r.room_number} · {r.room_name}</option>)}</select>}</Field><Field label={t("equipmentPage.status")}>{id=><select id={id} name="status" defaultValue={equipment.status||"OPERATIONAL"}>{equipmentStatuses.map(v=><option key={v} value={v}>{t(v)}</option>)}</select>}</Field><SubmitButton busy={action.busy} busyLabel={t("equipmentPage.saving")}>{t(edit?"equipmentPage.save":"equipmentPage.addButton")}</SubmitButton></form></Modal>}
function RemoveDialog({equipment,onClose,onRemoved}){const {t}=useLanguage();const action=useAction();return <Modal title={t("equipmentPage.removeDialog")} onClose={onClose}><p>{t("equipmentPage.removeConfirm")} <strong>{equipment.equipment_name}</strong>?</p><ErrorAlert message={t(action.error)}/><div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>{t("common.cancel")}</button><button type="button" className="button" disabled={action.busy} onClick={()=>action.run(async()=>{await equipmentService.remove(equipment.equipment_id);onRemoved()})}>{action.busy?t("equipmentPage.saving"):t("equipmentPage.remove")}</button></div></Modal>}
