import { useState } from "react";
import { Download, FileBarChart } from "lucide-react";
import { useLanguage } from "../context/LanguageContext";
import { useResource } from "../hooks/useResource";
import { buildingService } from "../services/buildingService";
import { reportService } from "../services/reportService";
import { EmptyState, Field, PageHeader, ResourceState } from "../components/UI";

const types = ["MAINTENANCE_REQUESTS", "EQUIPMENT_HEALTH", "ENERGY_SUSTAINABILITY", "COMFORT", "ALERTS_INCIDENTS", "SAFETY_SECURITY"];
export default function Reports() {
  const { t } = useLanguage(); const [type, setType] = useState(types[0]); const [filters, setFilters] = useState({ building_id: "", status: "", category: "", start_date: "", end_date: "" });
  const report = useResource(() => reportService.get(type, filters), `${type}:${JSON.stringify(filters)}`); const buildings = useResource(buildingService.list);
  const update = (name, value) => setFilters((current) => ({ ...current, [name]: value }));
  const exportCsv = () => { const data = report.data; if (!data) return; const esc = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`; const csv = [data.columns.map(esc).join(","), ...data.rows.map((row) => data.columns.map((column) => esc(row[column])).join(","))].join("\r\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `${type.toLowerCase()}-report.csv`; link.click(); URL.revokeObjectURL(url); };
  return <><PageHeader eyebrow={t("reports.title")} title={t("reports.title")} description={t("reports.results")}><button className="button" onClick={exportCsv} disabled={!report.data?.rows.length}><Download size={17}/>{t("reports.export")}</button></PageHeader>
    <section className="panel filter-panel"><div className="filters"><Field label={t("reports.type")}>{(id) => <select id={id} value={type} onChange={(e) => setType(e.target.value)}>{types.map((value) => <option key={value} value={value}>{t(value)}</option>)}</select>}</Field><Field label={t("reports.building")}>{(id) => <select id={id} value={filters.building_id} onChange={(e) => update("building_id", e.target.value)}><option value="">{t("reports.allBuildings")}</option>{buildings.data?.map((b) => <option key={b.building_id} value={b.building_id}>{b.building_name}</option>)}</select>}</Field><Field label={t("reports.status")}>{(id) => <input id={id} value={filters.status} onChange={(e) => update("status", e.target.value.toUpperCase())} placeholder={t("reports.statusHint")} />}</Field><Field label={t("reports.category")}>{(id) => <input id={id} value={filters.category} onChange={(e) => update("category", e.target.value.toUpperCase())} placeholder={t("reports.categoryHint")} />}</Field><Field label={t("reports.from")}>{(id) => <input id={id} type="date" value={filters.start_date} onChange={(e) => update("start_date", e.target.value)} />}</Field><Field label={t("reports.to")}>{(id) => <input id={id} type="date" value={filters.end_date} onChange={(e) => update("end_date", e.target.value)} />}</Field><button className="text-button" onClick={() => setFilters({ building_id: "", status: "", category: "", start_date: "", end_date: "" })}>{t("reports.clear")}</button></div></section>
    <ResourceState resource={report} copy={{ loading: t("reports.loading"), retry: t("reports.retry"), error: t }}>{report.data?.rows.length ? <section className="panel"><div className="panel-heading"><h2>{t("reports.results")}</h2><span className="count-label">{report.data.rows.length} {t("reports.rows")}</span></div><div className="report-summary">{Object.entries(report.data.summary).map(([key,value]) => <span key={key}><strong>{value ?? "—"}</strong> {t(`reports.${key}`)}</span>)}</div><div className="table-scroll management-table"><table><thead><tr>{report.data.columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{report.data.rows.map((row,index) => <tr key={index}>{report.data.columns.map((column) => <td key={column}>{row[column] ?? "—"}</td>)}</tr>)}</tbody></table></div></section> : <EmptyState title={t("reports.empty")} description={t("reports.emptyDescription")} />}</ResourceState>
  </>;
}
